package view;

import dao.ClienteDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 * JFrame mostra uma lista com todos os clientes cadastrados
 * @author guise
 */
public class BuscaCliente extends javax.swing.JFrame {
    
    //Nesta tela, a restrição de usuários não esconde nenhum botão
         
    public BuscaCliente() {
        
        initComponents(); 
     
        mapearTeclas();
        
        ClienteDAO clienteDAO = new ClienteDAO();
        List<Cliente> listaCliente = clienteDAO.listar();
        preencherTabela(listaCliente);
        
           
        //Esconde a coluna de ID
        tblClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tblClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblClientes.getColumnModel().getColumn(0).setWidth(0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtPesquisar = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        cbxFiltros = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnVerDetalhes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLayeredPane1.setToolTipText("Tela para pesquisar por um cliente");

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisar.setToolTipText("Pesquise sobre o cliente (Alt + 1)");
        txtPesquisar.setNextFocusableComponent(cbxFiltros);
        txtPesquisar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarCaretUpdate(evt);
            }
        });

        lblPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPesquisar.setLabelFor(txtPesquisar);
        lblPesquisar.setText("Pesquisar:");

        cbxFiltros.setBackground(new java.awt.Color(130, 201, 198));
        cbxFiltros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtros", "Nome", "CPF" }));
        cbxFiltros.setToolTipText("Aplique um filtro sobre o cliente (TAB)");
        cbxFiltros.setNextFocusableComponent(btnVerDetalhes);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome completo", "CPF", "Bairro", "N Residencial", "Rua"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Voltar para menu principal (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtPesquisar);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnVerDetalhes.setBackground(new java.awt.Color(9, 132, 127));
        btnVerDetalhes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVerDetalhes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalhes.setText("Ver detalhes");
        btnVerDetalhes.setToolTipText("Clique para ver detalhes sobre o cliente (Alt + D)");
        btnVerDetalhes.setNextFocusableComponent(btnVoltar);
        btnVerDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalhesActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(txtPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxFiltros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVerDetalhes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnVerDetalhes))
                .addGap(19, 19, 19))
        );

        txtPesquisar.getAccessibleContext().setAccessibleName("Campo Pesquisar");
        txtPesquisar.getAccessibleContext().setAccessibleDescription("Campo para pesquise sobre o cliente");
        cbxFiltros.getAccessibleContext().setAccessibleName("ComboBox Filtros");
        cbxFiltros.getAccessibleContext().setAccessibleDescription("Caixa para aplicar um filtro sobre o cliente");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar ");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Clique para voltar para o menu principal");
        btnVerDetalhes.getAccessibleContext().setAccessibleName("Botão Ver detalhes");
        btnVerDetalhes.getAccessibleContext().setAccessibleDescription("Clique para ver detalhes sobre o cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /**
        * Entra no perfil do cliente selecionado
        * @param evt 
        */
    private void btnVerDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalhesActionPerformed
        try {
        abrirPerfilCliente();
        
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        
        } 
    }//GEN-LAST:event_btnVerDetalhesActionPerformed
        /** 
        * Volta para o Menu Principal
        * @param evt 
        */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

        /**
        * Aplica um filtro de acordo com a caixa "Filtros"
        * @param evt 
        */
    private void txtPesquisarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarCaretUpdate
        aplicarFiltro();
    }//GEN-LAST:event_txtPesquisarCaretUpdate

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerDetalhes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxFiltros;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    //Métodos usados
    



    
        /**
        * Preenche tblClientes com os dados da base de dados
        * @param lista 
        */
        protected void preencherTabela(List<Cliente> lista) {

        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();

        // Remove todas as linhas atuais
        modelo.setRowCount(0);

       
        for (Cliente c : lista) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf(),
                c.getBairro(),
                c.getRua(),
                c.getResidencial()
            });
        }
    }
            
        
    
     /**
     * Preenche tblClientes de acordo com o filtro selecionado
     */
     protected void aplicarFiltro(){
         String texto = txtPesquisar.getText();
         int filtro = cbxFiltros.getSelectedIndex();
         ClienteDAO clienteDAO = new ClienteDAO();
         List <Cliente> lista;
         
         if (texto.length() >= 1){
             lista = clienteDAO.listaComFiltro(filtro, texto);
            
         }
         
         else {
             lista = clienteDAO.listar();
         }
         
         preencherTabela(lista);
           
     }
    
    
    /**
     * Abre o perfil do cliente selecionado com o mouse
     */ 
     protected void abrirPerfilCliente(){
         int linha = tblClientes.getSelectedRow();

         if (linha == -1) {
         JOptionPane.showMessageDialog(this, "Selecione um cliente.");
        }
        
         else{
        // Coluna 0 contém a ID
         int idCliente = (int) tblClientes.getValueAt(linha, 0);
         
         ClienteDAO clienteDAO = new ClienteDAO();
         Cliente clienteSelecionado = clienteDAO.buscarId(idCliente);
         
         PerfilCliente telaPerfil = new PerfilCliente(clienteSelecionado);
         telaPerfil.setVisible(true);
         
         //Fecha esta tela
         dispose();
         }
     }
     
     
    /** 
     * Mapeia os atalhos para a tela
     */
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblPesquisar.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + D
        btnVerDetalhes.setMnemonic(KeyEvent.VK_D);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);    
    }   
}   
