package view;

import dao.EmprestimoDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Emprestimo;


/**
 * JFrame mostra uma lista com todos os emprestimos cadastrados
 * @author guise
 */
public class BuscaEmprestimo extends javax.swing.JFrame {

    //Nesta tela, a restrição de usuários não esconde nenhum botão
    
    public BuscaEmprestimo() {
        initComponents();
        mapearTeclas();
        
        
        EmprestimoDAO empDAO = new EmprestimoDAO();
        List<Emprestimo> listaEmp = empDAO.listar();
        preencherTabela(listaEmp);
        
           
        //Esconde a coluna de ID, ID_cliente e ID_jogo
        tblEmprestimos.getColumnModel().getColumn(0).setMinWidth(0);
        tblEmprestimos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblEmprestimos.getColumnModel().getColumn(0).setWidth(0);
        
        tblEmprestimos.getColumnModel().getColumn(1).setMinWidth(0);
        tblEmprestimos.getColumnModel().getColumn(1).setMaxWidth(0);
        tblEmprestimos.getColumnModel().getColumn(1).setWidth(0);
        
        tblEmprestimos.getColumnModel().getColumn(2).setMinWidth(0);
        tblEmprestimos.getColumnModel().getColumn(2).setMaxWidth(0);
        tblEmprestimos.getColumnModel().getColumn(2).setWidth(0);
        
           
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtPesquisar = new javax.swing.JTextField();
        cbxFiltros = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimos = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        lblPesquisar = new javax.swing.JLabel();
        btnVerDetalhes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busca de empréstimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        jLayeredPane1.setToolTipText("Pesquise sobre um empréstimo");

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisar.setToolTipText("Pesquise sobre o empréstimo (Alt + 1)");
        txtPesquisar.setNextFocusableComponent(cbxFiltros);
        txtPesquisar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarCaretUpdate(evt);
            }
        });

        cbxFiltros.setBackground(new java.awt.Color(130, 201, 198));
        cbxFiltros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtros", "Nome do cliente", "CPF" }));
        cbxFiltros.setToolTipText("Selecione um filtro para aplicar sobre o empréstimo (TAB)");
        cbxFiltros.setNextFocusableComponent(btnVerDetalhes);

        tblEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "id_cliente", "id_jogo", "Nome do cliente", "CPF", "Titulo do jogo", "Data do empréstimo", "Devolução"
            }
        ));
        jScrollPane1.setViewportView(tblEmprestimos);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique para voltar ao menu principal (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtPesquisar);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPesquisar.setLabelFor(txtPesquisar);
        lblPesquisar.setText("Pesquisar:");

        btnVerDetalhes.setBackground(new java.awt.Color(9, 132, 127));
        btnVerDetalhes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVerDetalhes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalhes.setText("Ver detalhes");
        btnVerDetalhes.setToolTipText("Clique para ver o perfil de um empréstimo (Alt + D)");
        btnVerDetalhes.setNextFocusableComponent(btnVoltar);
        btnVerDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalhesActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(txtPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxFiltros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVerDetalhes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(btnVoltar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerDetalhes)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnVerDetalhes))
                .addGap(17, 17, 17))
        );

        txtPesquisar.getAccessibleContext().setAccessibleName("Campo Pesquisar");
        txtPesquisar.getAccessibleContext().setAccessibleDescription("Campor para pesquisar sobre o empréstimo");
        cbxFiltros.getAccessibleContext().setAccessibleName("ComboBox Filtros");
        cbxFiltros.getAccessibleContext().setAccessibleDescription("Clique para aplicar um filtro sobre o empréstimo");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar ao menu principal");
        btnVerDetalhes.getAccessibleContext().setAccessibleName("Botão Ver detalhes");
        btnVerDetalhes.getAccessibleContext().setAccessibleDescription("Botão para ver os detalhes sobre um empréstimo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /** 
        * Volta para o Menu Principal
        * @param evt 
        */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
       
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
        /**
        * Entra no perfil do emprestimo selecionado
        * @param evt 
        */
    private void btnVerDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalhesActionPerformed
        try {
        abrirPerfilEmprestimo();
        
        } catch (Exception e ) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnVerDetalhesActionPerformed
        /**
        * Aplica um filtro de acordo com a caixa "Filtros"
        * @param evt 
        */
    private void txtPesquisarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarCaretUpdate
        aplicarFiltro();
    }//GEN-LAST:event_txtPesquisarCaretUpdate

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerDetalhes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxFiltros;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JTable tblEmprestimos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

// Métodos usados
    
        /**
        * Preenche tblEmprestimos com os dados da base de dados
        * @param lista 
        */
        protected void preencherTabela(List<Emprestimo> lista) {

        DefaultTableModel modelo = (DefaultTableModel) tblEmprestimos.getModel();

        // Remove todas as linhas atuais
        modelo.setRowCount(0);

       
        for (Emprestimo emp: lista) {
            modelo.addRow(new Object[]{
                emp.getId(),
                emp.getFkCliente(),
                emp.getFkJogo(),
                emp.getNomeCliente(),
                emp.getCpf(),
                emp.getTituloJogo(),
                emp.getDataEmp(),
                emp.getDevolucao(),
            });
        }
    }

        
    
    /**
     * Preenche tblEmprestimos de acordo com o filtro selecionado
     */
     protected void aplicarFiltro(){
         String texto = txtPesquisar.getText();
         int filtro = cbxFiltros.getSelectedIndex();
         EmprestimoDAO empDAO = new EmprestimoDAO();
         List <Emprestimo> lista;
         
         if (texto.length() >= 1){
             lista = empDAO.listaComFiltro(filtro, texto);
            
         }
         
         else {
             lista = empDAO.listar();
         }
         
         preencherTabela(lista);
           
     }
    
     
    /**
     * Abre o perfil do cliente selecionado com o mouse
     */ 
     protected void abrirPerfilEmprestimo(){
         int linha = tblEmprestimos.getSelectedRow();

         if (linha == -1) {
         JOptionPane.showMessageDialog(this, "Selecione um empréstimo.");
        }
         
         else{
         
        // Coluna 0 contém a ID
         int idEmprestimo = (int) tblEmprestimos.getValueAt(linha, 0);
         
         EmprestimoDAO empDAO = new EmprestimoDAO();
         Emprestimo empSelecionado = empDAO.buscarId(idEmprestimo);
         
         PerfilEmprestimo telaPerfil = new PerfilEmprestimo(empSelecionado);
         telaPerfil.setVisible(true);
         
         //Fecha esta tela
         dispose();
         }
     }
    
    /**
     * Mapeia os atalhos para a tela
     */ 
     protected void mapearTeclas(){
        
        
        // Alt + 1
        lblPesquisar.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + D
        btnVerDetalhes.setMnemonic(KeyEvent.VK_D);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);                                   
    }
    
    
}
