package view;

import dao.JogoDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import model.Jogo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/**
 * JFrame mostra uma lista com todos os jogos cadastrados
 * @author guise
 */
public class BuscaJogo extends javax.swing.JFrame {

    //Nesta tela, a restrição de usuários não esconde nenhum botão
    
    public BuscaJogo() {
        initComponents();
        
        mapearTeclas();
        
        JogoDAO jogoDAO = new JogoDAO();
        List<Jogo> listaJogo = jogoDAO.listar();
        preencherTabela(listaJogo);
        
    
        //Esconde a coluna de ID
        tblJogos.getColumnModel().getColumn(0).setMinWidth(0);
        tblJogos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblJogos.getColumnModel().getColumn(0).setWidth(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblPesquisar = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogos = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        cbxFiltros = new javax.swing.JComboBox<>();
        btnVerDetalhes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busca de jogos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N
        jLayeredPane1.setToolTipText("Tela para pesquisar sobre jogo");

        lblPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPesquisar.setLabelFor(txtPesquisar);
        lblPesquisar.setText("Pesquisar:");

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisar.setToolTipText("Pesquise sobre o jogo (Alt + 1)");
        txtPesquisar.setNextFocusableComponent(cbxFiltros);
        txtPesquisar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarCaretUpdate(evt);
            }
        });

        tblJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Genêro", "Plataforma", "Ano de lançamento", "Desenvolvedora", "Cópias"
            }
        ));
        jScrollPane1.setViewportView(tblJogos);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Voltar para o menu principal (Alt +V)");
        btnVoltar.setNextFocusableComponent(txtPesquisar);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        cbxFiltros.setBackground(new java.awt.Color(130, 201, 198));
        cbxFiltros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtros", "Título", "Plataforma", "Desenvolvedora" }));
        cbxFiltros.setToolTipText("Aplique um filtro sobre o jogo (TAB)");
        cbxFiltros.setNextFocusableComponent(btnVerDetalhes);

        btnVerDetalhes.setBackground(new java.awt.Color(9, 132, 127));
        btnVerDetalhes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVerDetalhes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalhes.setText("Ver detalhes");
        btnVerDetalhes.setToolTipText("Clique para ver detalhes sobre o jogo (Alt + D)");
        btnVerDetalhes.setNextFocusableComponent(btnVoltar);
        btnVerDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalhesActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxFiltros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVerDetalhes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnVerDetalhes))
                .addGap(17, 17, 17))
        );

        txtPesquisar.getAccessibleContext().setAccessibleName("Campo Pesquisar");
        txtPesquisar.getAccessibleContext().setAccessibleDescription("Campo para pesquisar sobre o jogo");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar para o menu principal");
        btnVerDetalhes.getAccessibleContext().setAccessibleName("Botão Ver detalhes");
        btnVerDetalhes.getAccessibleContext().setAccessibleDescription("Botão para ver detalhes sobre o jogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
       /**
        * Volta para o MenuPrincipal (mas não fecha essa tela)
        * @param evt
        */ 
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
       /**
        * Entra no perfil do jogo selecionado
        * @param evt 
        */
    private void btnVerDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalhesActionPerformed
        try {
        abrirPerfil();
        
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
        
    }//GEN-LAST:event_btnVerDetalhesActionPerformed

           /**
            * Aplica um filtro de acordo com a caixa "Filtros"
            * @param evt 
            */
    private void txtPesquisarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarCaretUpdate
             aplicarFiltro();
    }//GEN-LAST:event_txtPesquisarCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerDetalhes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxFiltros;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JTable tblJogos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    //Métodos usados
    
    
            /**
            * Preenche tblJogos com os dados da base de dados
            * @param lista 
            */
            protected void preencherTabela(List<Jogo> lista) {

            DefaultTableModel modelo = (DefaultTableModel) tblJogos.getModel();

            // Remove todas as linhas atuais
            modelo.setRowCount(0);


            for (Jogo j : lista) {
                modelo.addRow(new Object[]{
                    j.getId(),
                    j.getTitulo(),
                    j.getGenero(),
                    j.getPlataforma(),
                    j.getLancamento(),
                    j.getDesenvolvedora(),
                    j.getCopias()
                });
            }
        }
    
    /**
     * Preenche tblJogos de acordo com o filtro selecionado
     */
     protected void aplicarFiltro(){
         String texto = txtPesquisar.getText();
         int filtro = cbxFiltros.getSelectedIndex();
         JogoDAO jogoDAO = new JogoDAO();
         List <Jogo> lista;

         if (texto.length() >= 1){
             lista = jogoDAO.listaComFiltro(filtro, texto);

         }

         else {
             lista = jogoDAO.listar();
         }

         preencherTabela(lista);

     }
             
     /**
     * Abre o perfil do jogo selecionado com o mouse
     */ 
     protected void abrirPerfil(){
         int linha = tblJogos.getSelectedRow();

         if (linha == -1) {
         JOptionPane.showMessageDialog(this, "Selecione um jogo.");
        }

         else{
         int idJogo = (int) tblJogos.getValueAt(linha, 0);

         JogoDAO jogoDAO = new JogoDAO();
         Jogo jogoSelecionado = jogoDAO.buscarId(idJogo);

         PerfilJogo telaPerfil = new PerfilJogo(jogoSelecionado);
         telaPerfil.setVisible(true);
         
         //Fecha essa tela
         dispose();
         }
     }


    
    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblPesquisar.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + D
        btnVerDetalhes.setMnemonic(KeyEvent.VK_D);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);  
    }   
}


