package view;

import dao.UsuarioDAO;
import java.awt.event.KeyEvent;
import model.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 * JFrame mostra uma lista com todos os usuarios cadastrados
 * @author guise
 */
public class BuscaUsuario extends javax.swing.JFrame {

    public BuscaUsuario() {
        initComponents();
        
        mapearTeclas();
        
        UsuarioDAO usuariosDAO = new UsuarioDAO();
        List<Usuario> listaUsuario = usuariosDAO.listar();
        preencherTabela(listaUsuario);
           
        //Esconde a coluna de ID
        tblUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
        tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
        tblUsuarios.getColumnModel().getColumn(0).setWidth(0);
        
        tblUsuarios.getColumnModel().getColumn(2).setMinWidth(0);
        tblUsuarios.getColumnModel().getColumn(2).setMaxWidth(0);
        tblUsuarios.getColumnModel().getColumn(2).setWidth(0);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblPesquisar = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        cbxFiltros = new javax.swing.JComboBox<>();
        btnVerDetalhes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busca de usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N
        jLayeredPane1.setToolTipText("Tela para pesquisar por um usuário");

        lblPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPesquisar.setLabelFor(txtPesquisar);
        lblPesquisar.setText("Pesquisar:");
        lblPesquisar.setNextFocusableComponent(cbxFiltros);

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisar.setToolTipText("Pesquise por um usuário (Alt + 1)");
        txtPesquisar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarCaretUpdate(evt);
            }
        });

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome de usuario", "Senha", "Tipo de usuario"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Voltar para o menu principal  (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtPesquisar);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        cbxFiltros.setBackground(new java.awt.Color(130, 201, 198));
        cbxFiltros.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtros", "Nome Usuario" }));
        cbxFiltros.setToolTipText("Selecione um filtro (TAB)");
        cbxFiltros.setNextFocusableComponent(btnVerDetalhes);

        btnVerDetalhes.setBackground(new java.awt.Color(9, 132, 127));
        btnVerDetalhes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVerDetalhes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalhes.setText("Ver detalhes");
        btnVerDetalhes.setToolTipText("Ver detalhes do usuário (Alt + D)");
        btnVerDetalhes.setNextFocusableComponent(btnVoltar);
        btnVerDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalhesActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxFiltros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVerDetalhes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(lblPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(264, 264, 264)
                        .addComponent(btnVerDetalhes))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnVerDetalhes))
                .addGap(16, 16, 16))
        );

        txtPesquisar.getAccessibleContext().setAccessibleName("Campo Pesquisar");
        txtPesquisar.getAccessibleContext().setAccessibleDescription("Pesquise por um usuário na tabela");
        cbxFiltros.getAccessibleContext().setAccessibleName("ComboBox Filtros");
        cbxFiltros.getAccessibleContext().setAccessibleDescription("Selecione um filtro para aplicar sobre a barra de Pesquisa");
        btnVerDetalhes.getAccessibleContext().setAccessibleName("Botão Ver Detalhes");
        btnVerDetalhes.getAccessibleContext().setAccessibleDescription("Botão para ver o perfil de um usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       /**
        * Volta para MenuPrincipal
        */ 
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
       /**
        * Entra no perfil do usuário selecionado
        */ 
    private void btnVerDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalhesActionPerformed
        try {
        abrirPerfilUsuario();
        
        } catch (Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnVerDetalhesActionPerformed
        /**
        * Aplica um filtro de acordo com a caixa "Filtros"
        * @param evt 
        */
    private void txtPesquisarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarCaretUpdate
        aplicarFiltro();
    }//GEN-LAST:event_txtPesquisarCaretUpdate

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerDetalhes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxFiltros;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    /* 
    * Métodos usados por esta JFrame
    */
    
        /**
        * Preenche tblUsuarios com os dados da base de dados
        * @param lista 
        */
        protected void preencherTabela(List<Usuario> lista) {

        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();

        // Remove todas as linhas atuais
        modelo.setRowCount(0);

        
        for (Usuario u : lista) {
            modelo.addRow(new Object[]{
                u.getId(),
                u.getNomeUsuario(),
                u.getSenha(),
                u.getTipoUsuario(),
            });
        }
    }

    
         /**
         * Preenche tblUsuarios de acordo com o filtro selecionado
         */
         protected void aplicarFiltro(){
             String texto = txtPesquisar.getText();
             int filtro = cbxFiltros.getSelectedIndex();
             UsuarioDAO usuarioDAO = new UsuarioDAO();
             List <Usuario> lista;
         
         if (texto.length() >= 1){
             lista = usuarioDAO.listaComFiltro(filtro, texto);
            
         }
         
         else {
             lista = usuarioDAO.listar();
         }
         
         preencherTabela(lista);

         }
    
    
        /**
         * Abre o perfil do usuario selecionado com o mouse
         */ 
         protected void abrirPerfilUsuario(){
             int linha = tblUsuarios.getSelectedRow();

             if (linha == -1) {
             JOptionPane.showMessageDialog(this, "Selecione um usuario.");
            }

            else{
            // Coluna 0 contém a ID
             int idUsuario = (int) tblUsuarios.getValueAt(linha, 0);

             UsuarioDAO usuarioDAO = new UsuarioDAO();
             Usuario usuarioSelecionado = usuarioDAO.buscarId(idUsuario);

             PerfilUsuario telaPerfil = new PerfilUsuario(usuarioSelecionado);
             telaPerfil.setVisible(true);
             
             //Fecha esta tela
             dispose();
             }
         }
    
    
    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblPesquisar.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + D
        btnVerDetalhes.setMnemonic(KeyEvent.VK_D);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);        
        
        
        
    }
}
