package view;

import dao.UsuarioDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Usuario;
import static utilidades.ChaveCriptografica.getMD5;

/**
 * JFrame usada para cadastrar um novo usuario
 * @author guise
 */

public class CadastroUsuario extends javax.swing.JFrame {

   
    
    public CadastroUsuario() {
      
        initComponents();
        mapearTeclas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblNomeUsuario = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        cbxTipoUsuario = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N
        jLayeredPane1.setToolTipText("");

        lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeUsuario.setLabelFor(txtNomeUsuario);
        lblNomeUsuario.setText("Nome de usuário:");

        txtNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomeUsuario.setToolTipText("Insirar nome de usuário (Alt +1)");
        txtNomeUsuario.setNextFocusableComponent(txtSenha);

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSenha.setToolTipText("Insira senha (Alt +2)");
        txtSenha.setNextFocusableComponent(cbxTipoUsuario);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSenha.setLabelFor(txtSenha);
        lblSenha.setText("Senha:");

        lblTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTipoUsuario.setLabelFor(cbxTipoUsuario);
        lblTipoUsuario.setText("Tipo de usuário:");

        cbxTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Atendente", "Estoquista", "Gerente", "Supervisor" }));
        cbxTipoUsuario.setToolTipText("Selecione tipo de usuário (Alt + 3)");
        cbxTipoUsuario.setNextFocusableComponent(btnCadastrar);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Voltar para o Menu principal (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtNomeUsuario);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(9, 132, 127));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Cadastrar usuário (Alt + C)");
        btnCadastrar.setNextFocusableComponent(btnVoltar);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblNomeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNomeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblNomeUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblTipoUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addGap(15, 15, 15))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeUsuario)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addGap(36, 36, 36))
        );

        txtNomeUsuario.getAccessibleContext().setAccessibleName("Campo Nome de usuário");
        txtNomeUsuario.getAccessibleContext().setAccessibleDescription("Campo para inserir o Nome de usuário");
        txtSenha.getAccessibleContext().setAccessibleName("Campo Senha");
        txtSenha.getAccessibleContext().setAccessibleDescription("Campo para inserir a Senha");
        cbxTipoUsuario.getAccessibleContext().setAccessibleName("ComboBoxTipo de usuário");
        cbxTipoUsuario.getAccessibleContext().setAccessibleDescription("Caixa para selecionar tipo de usuário");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar ao Menu Principal");
        btnCadastrar.getAccessibleContext().setAccessibleName("Botão Cadastrar");
        btnCadastrar.getAccessibleContext().setAccessibleDescription("Botão para cadastrar o usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /**
        * Voltar para o MenuPrincipal
        * @param evt
        */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
        /**
         * Cadastra um novo usuario
         * @param evt 
         */
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try{
            validarCampos();
            
        cadastrarUsuario();
        
        dispose();
        
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxTipoUsuario;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables

// Métodos usados por esta JFrame
    
    /**
     * Cadastra um novo usuario na tabela "usuarios".
     * Criptografa a senha.
     */
    protected void cadastrarUsuario(){
        Usuario objUsuario = new Usuario();
        
        String nome = txtNomeUsuario.getText();
        String senha = txtSenha.getText();
        String tipoSelecionado = cbxTipoUsuario.getSelectedItem().toString();
        
        String senhaCripto = getMD5(senha);
        
        
        objUsuario.setNomeUsuario(nome);
        objUsuario.setSenha(senhaCripto);
        objUsuario.setTipoUsuario(tipoSelecionado);
        
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.inserir(objUsuario);
        
        // Mostra mensagem de Sucesso
        JOptionPane.showMessageDialog(
            this,
            "Cadastro bem-sucedido!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
        
    }

    
    /**
     * Impede que campos vazios sejam aceitos
     * @throws java.lang.Exception
     */ 
    protected void validarCampos() throws Exception {
        
        String nomeUsuario = txtNomeUsuario.getText();
        String senha = txtSenha.getText();
        String tipo = cbxTipoUsuario.getSelectedItem().toString();
        
        
        if (nomeUsuario.isEmpty()){
            throw new Exception ("Campo Nome de usuário não pode ser vazio.");
        }
        
        if (senha.isEmpty()){
            throw new Exception ("Campo Senha não pode ser vazio.");
        }
        
        if (tipo.equals("Selecione")){
            throw new Exception ("Escolha um tipo de usuário.");
        }
    }
    
    
    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblNomeUsuario.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblSenha.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblTipoUsuario.setDisplayedMnemonic(KeyEvent.VK_3);        
        
        // Alt + C
        btnCadastrar.setMnemonic(KeyEvent.VK_C);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);
        
    }
}
