package view;

import dao.ClienteDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 * JFrame usada para cadastrar um novo cliente
 * @author guise
 */
public class CadastroCliente extends javax.swing.JFrame {

   
    

    public CadastroCliente() {
       
        initComponents();
        mapearTeclas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        txtResidencial = new javax.swing.JTextField();
        lblResidencial = new javax.swing.JLabel();
        lblEndereço = new javax.swing.JLabel();
        lblDadosPessoais = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N
        jLayeredPane1.setToolTipText("Insira os dados do cliente");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNome.setLabelFor(txtNome);
        lblNome.setText("Nome e sobrenome:");
        lblNome.setToolTipText("");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNome.setToolTipText("Inserir nome e sobrenome (Alt + 1)");
        txtNome.setNextFocusableComponent(txtCpf);

        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCpf.setToolTipText("Inserir CPF (Alt + 2)");
        txtCpf.setNextFocusableComponent(txtBairro);

        lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCpf.setLabelFor(txtCpf);
        lblCpf.setText("CPF:");
        lblCpf.setToolTipText("");

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBairro.setLabelFor(txtBairro);
        lblBairro.setText("Bairro:");
        lblBairro.setToolTipText("");

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtBairro.setToolTipText("Inserir Bairro (Alt + 3)");
        txtBairro.setNextFocusableComponent(txtRua);

        txtRua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtRua.setToolTipText("Inserir Rua (Alt + 4)");
        txtRua.setNextFocusableComponent(txtResidencial);

        lblRua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRua.setLabelFor(txtRua);
        lblRua.setText("Rua:");

        txtResidencial.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtResidencial.setToolTipText("Inserir Número Residencial (Alt + 5)");
        txtResidencial.setNextFocusableComponent(btnCadastrar);

        lblResidencial.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblResidencial.setLabelFor(txtResidencial);
        lblResidencial.setText("N Residencial:");

        lblEndereço.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEndereço.setForeground(new java.awt.Color(51, 0, 153));
        lblEndereço.setText("Endereço");

        lblDadosPessoais.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDadosPessoais.setForeground(new java.awt.Color(51, 0, 153));
        lblDadosPessoais.setText("Dados Pessoais");

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Voltar para menu principal (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtNome);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(9, 132, 127));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Cadastrar cliente (Alt + C)");
        btnCadastrar.setNextFocusableComponent(btnVoltar);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtResidencial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblResidencial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblEndereço, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDadosPessoais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblResidencial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEndereço)
                            .addComponent(lblDadosPessoais))
                        .addGap(0, 98, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblDadosPessoais)
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(lblEndereço)
                .addGap(34, 34, 34)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResidencial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnCadastrar))
                .addGap(26, 26, 26))
        );

        txtNome.getAccessibleContext().setAccessibleName("Campo Nome e sobrenome:");
        txtNome.getAccessibleContext().setAccessibleDescription("Campo para  inserir nome e sobrenome");
        txtCpf.getAccessibleContext().setAccessibleName("Campo CPF");
        txtCpf.getAccessibleContext().setAccessibleDescription("Campo para inserir CPF ");
        txtBairro.getAccessibleContext().setAccessibleName("Campo Bairro");
        txtBairro.getAccessibleContext().setAccessibleDescription("Campo para  inserir o Bairro");
        txtRua.getAccessibleContext().setAccessibleName("Campo Rua");
        txtRua.getAccessibleContext().setAccessibleDescription("Campo para inserir a Rua");
        txtResidencial.getAccessibleContext().setAccessibleName("Campo N Residencial");
        txtResidencial.getAccessibleContext().setAccessibleDescription("Campo para inserir o Número Residencial");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar para o menu principal");
        btnCadastrar.getAccessibleContext().setAccessibleName("Botão Cadastrar");
        btnCadastrar.getAccessibleContext().setAccessibleDescription("Botão para cadastrar o cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       /**
        * Voltar para o MenuPrincipal
        * @param evt
        */ 
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();  
    }//GEN-LAST:event_btnVoltarActionPerformed
        /**
         * Cadastra um novo cliente
         * @param evt 
         */
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try{
            validarCampos();
            
        cadastrarCliente();
        
        dispose();
        
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDadosPessoais;
    private javax.swing.JLabel lblEndereço;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblResidencial;
    private javax.swing.JLabel lblRua;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtResidencial;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables

  // Métodos usados por esta JFrame
    
    /**
     * Cadastra um novo cliente na tabela "clientes"
     */
    protected void cadastrarCliente(){
        Cliente objCliente = new Cliente();
        
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String bairro = txtBairro.getText();
        String rua = txtRua.getText();
        int residencial = Integer.parseInt(txtResidencial.getText());
        
        
        objCliente.setNome(nome);
        objCliente.setCpf(cpf);
        objCliente.setBairro(bairro);
        objCliente.setRua(rua);
        objCliente.setResidencial(residencial);
        
        ClienteDAO clienteDAO = new ClienteDAO();
        clienteDAO.inserir(objCliente);
        
        // Mostra mensagem de Sucesso
        JOptionPane.showMessageDialog(
            this,
            "Cadastro bem-sucedido!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
        
    }
     
    
    /**
     * Garante que os campos não estejam vazios e no formato correto
     */
    protected void validarCampos() throws Exception {
        String nome = txtNome.getText();
        String cpf = txtCpf.getText().trim();
        String bairro = txtBairro.getText();
        String rua = txtRua.getText();
        
        String residencialTexto = txtResidencial.getText().trim();
        
        //NOME
        //Nome e Sobrenome não pode estar vazio
        if (nome.isEmpty()){
            throw new Exception ("Campo Nome e Sobrenome não pode ser vazio.");
        }
        
        //Nome aceita apenas letras e nome completo 
        if (!nome.matches("^[\\p{L} ]+$")){
            throw new Exception ("Campo Nome e Sobrenome deve conter apenas letras e espaços.");
        }
        
        
        // CPF
        //CPF não pode estar vazio
        if (cpf.isEmpty()) {
            throw new Exception ("CPF não pode ser vazio.");
        }
        
        // CPF só aceita números e no formato "000.000.000-00" 
        if (!cpf.matches("^\\d{3}\\.\\d{3}\\.\\d{3}[-\\.]\\d{2}$") || !cpf.matches("^[0-9.-]+$")){
            throw new Exception ("CPF aceita somente números e no seguinte formato: 000.000.000-00 ou 000.000.000.00");
        }
        
        
        //BAIRRO
        //Bairro não pode estar vazio
        if(bairro.isEmpty()){
           throw new Exception ("Bairro não pode ser vazio.");
        }
        
        //Bairro aceita somente letras
        if (bairro.matches("^[0-9]+$")){
           throw new Exception ("Bairro aceita somente letras.");
        }
        
        
        //RUA
        //"Rua" não pode estar vazio
        if(rua.isEmpty()){
           throw new Exception ("Rua não pode ser vazio.");
        }
        
        //Rua aceita somente letras
        if (rua.matches("^[0-9]+$")){
           throw new Exception ("Rua aceita somente letras.");
        }
        
        
        //RESIDENCIAL
        // "N Residencial" não pode estar vazio
        if(residencialTexto.isEmpty()){
           throw new Exception ("Nº Residencial não pode ficar vazio.");
        }
        
        //"N Residencial" aceita somente  números
        if(!residencialTexto.matches("^[0-9]+$")){
           throw new Exception ("Nº Residencial deve conter apenas números.");
        }
        
        // Converte para int
        int residencialInt = Integer.parseInt(residencialTexto);

        // Verifica se é maior que zero
        if (residencialInt <= 0) {
            throw new Exception("Nº Residencial deve ser maior que zero.");
}
    }
    
    
    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblNome.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblCpf.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblBairro.setDisplayedMnemonic(KeyEvent.VK_3);

        // Alt + 4
        lblRua.setDisplayedMnemonic(KeyEvent.VK_4); 
        
        // Alt + 5
        lblResidencial.setDisplayedMnemonic(KeyEvent.VK_5);   
        
        // Alt + C
        btnCadastrar.setMnemonic(KeyEvent.VK_C);
                
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);
        
    }
}
