package view;

import dao.EmprestimoDAO;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import model.Cliente;
import model.Emprestimo;
import model.Jogo;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import utilidades.GuardarUsuario;

/**
 * JFrame usada para cadastrar um novo emprestimo
 * @author guise
 */
public class CadastroEmprestimo extends javax.swing.JFrame {
    
    private Cliente clienteSelecionado;
    private Jogo jogoSelecionado;
    
    public CadastroEmprestimo() {
        initComponents();
        
        mapearTeclas();
        
        
        // Clicar no campo "Nome" ou "CPF" abre uma lista secundaria de clientes
        txtNomeCliente.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        SwingUtilities.invokeLater(() -> {
            
            ListaSecundariaCliente tela = new ListaSecundariaCliente(cliente -> {
            
             //Recebe o cliente vindo da lista
            clienteSelecionado = cliente;   
                
            //Preeenche os campos "Nome do cliente" e "Cpf"   
            txtNomeCliente.setText(cliente.getNome());
            txtCpf.setText(cliente.getCpf());
            
            });
            tela.setVisible(true);
            JOptionPane.showMessageDialog(null,
               
                "Selecione um cliente da tabela para preencher os campos (Nome do cliente) e (CPF),"
                        + " e então, clique no botão (Inserir em empréstimo.",
                "Aviso",
                JOptionPane.INFORMATION_MESSAGE
            );
        });
        }
        
    });
        
        txtCpf.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        SwingUtilities.invokeLater(() -> {
            
            ListaSecundariaCliente tela = new ListaSecundariaCliente(cliente -> {
            
            //Recebe o cliente vindo da lista
            clienteSelecionado = cliente;     
                
            //Preeenche os campos "Nome do cliente" e "Cpf"   
            txtNomeCliente.setText(cliente.getNome());
            txtCpf.setText(cliente.getCpf());
            
            });
            tela.setVisible(true);
            JOptionPane.showMessageDialog(
                null,
                "Selecione um cliente da tabela para preencher os campos (Nome do cliente) e (CPF),"
                        + " e então, clique no botão (Inserir em empréstimo).",
                "Aviso",
                JOptionPane.INFORMATION_MESSAGE
            );
        });
        }
    });
    
    
        // Clicar no campo "Nome Jogo" abre uma lista secundaria de jogos
        txtNomeJogo.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        SwingUtilities.invokeLater(() -> {
            
            ListaSecundariaJogo tela = new ListaSecundariaJogo(jogo -> {
            
            //Recebe o cliente vindo da lista
            jogoSelecionado = jogo;    
                
            //Preeenche o campo "Nome de jogo" 
            txtNomeJogo.setText(jogo.getTitulo());
            
            });
            tela.setVisible(true);
            
            JOptionPane.showMessageDialog(
                null,
                "Selecione um jogo da tabela para preencher o campo (Nome do jogo),"
                        + " e então, clique no botão (Inserir em empréstimo).",
                "Aviso",
                JOptionPane.INFORMATION_MESSAGE
            );
        });
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblNomeJogo = new javax.swing.JLabel();
        txtNomeJogo = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        lblNomeCliente = new javax.swing.JLabel();
        txtDataEmprestimo = new javax.swing.JTextField();
        lblDataEmprestimo = new javax.swing.JLabel();
        lblDevolucao = new javax.swing.JLabel();
        txtDevolucao = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de empréstimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N

        lblNomeJogo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeJogo.setLabelFor(txtNomeJogo);
        lblNomeJogo.setText("Nome de jogo:");

        txtNomeJogo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomeJogo.setToolTipText("Clique para inserir o nome de um jogo (Alt + 3)");
        txtNomeJogo.setNextFocusableComponent(txtDataEmprestimo);

        txtNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomeCliente.setToolTipText("Clique para inserir  o nome do cliente (Alt + 1)");
        txtNomeCliente.setNextFocusableComponent(txtCpf);

        lblNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeCliente.setLabelFor(txtNomeCliente);
        lblNomeCliente.setText("Nome do cliente:");

        txtDataEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDataEmprestimo.setToolTipText("Insira a data do empréstimo (Alt + 4)");
        txtDataEmprestimo.setNextFocusableComponent(txtDevolucao);

        lblDataEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDataEmprestimo.setLabelFor(txtDataEmprestimo);
        lblDataEmprestimo.setText("Data de empréstimo:");
        lblDataEmprestimo.setToolTipText("");

        lblDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDevolucao.setLabelFor(txtDevolucao);
        lblDevolucao.setText("Data de devolução:");

        txtDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDevolucao.setToolTipText("Insira a data de devolução (Alt + 5)");
        txtDevolucao.setNextFocusableComponent(btnCadastrar);

        btnCadastrar.setBackground(new java.awt.Color(9, 132, 127));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Clique para cadastrar um empréstimo (Alt + C)");
        btnCadastrar.setNextFocusableComponent(btnVoltar);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique para voltar para o menu principal (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtNomeCliente);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCpf.setToolTipText("Clique para inserir o CPF de um cliente (Alt + 2)");
        txtCpf.setNextFocusableComponent(txtNomeJogo);

        lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCpf.setLabelFor(txtCpf);
        lblCpf.setText("CPF:");

        jLayeredPane1.setLayer(lblNomeJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNomeJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNomeCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNomeCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDataEmprestimo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDataEmprestimo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDevolucao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDevolucao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblDataEmprestimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblDevolucao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 107, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblNomeJogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblNomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(128, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addGap(24, 24, 24))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeJogo)
                    .addComponent(txtNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataEmprestimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDevolucao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnCadastrar))
                .addGap(21, 21, 21))
        );

        txtNomeJogo.getAccessibleContext().setAccessibleName("Campo Nome de jogo");
        txtNomeJogo.getAccessibleContext().setAccessibleDescription("Campo para inserir o nome de um jogo");
        txtNomeCliente.getAccessibleContext().setAccessibleName("Campo Nome do cliente");
        txtNomeCliente.getAccessibleContext().setAccessibleDescription("Campo para inserir o nome do cliente");
        txtDataEmprestimo.getAccessibleContext().setAccessibleName("Campo Data de empréstimo");
        txtDataEmprestimo.getAccessibleContext().setAccessibleDescription("Campo  para inserir a data em que foi o empréstimo");
        txtDevolucao.getAccessibleContext().setAccessibleName("Campo Data de devolução");
        txtDevolucao.getAccessibleContext().setAccessibleDescription("Campo para inserir a data de devolução do jogo");
        btnCadastrar.getAccessibleContext().setAccessibleName("Botão Cadastrar");
        btnCadastrar.getAccessibleContext().setAccessibleDescription("Botão para cadastrar um empréstimo");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar para o menu principal");
        txtCpf.getAccessibleContext().setAccessibleName("Campo CPF");
        txtCpf.getAccessibleContext().setAccessibleDescription("Campo para inserir o CPF de um cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       /**
        * Volta para o MenuPrincipal
        */ 
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
        /**
         * Cadastra um novo emprestimo
         * @param evt 
         */ 
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
        validarCampos();
        cadastrarEmprestimo();    
       
          dispose();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }   
    }//GEN-LAST:event_btnCadastrarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataEmprestimo;
    private javax.swing.JLabel lblDevolucao;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeJogo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataEmprestimo;
    private javax.swing.JTextField txtDevolucao;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeJogo;
    // End of variables declaration//GEN-END:variables

//Métodos usados
    
    
     /**
     * Cadastra um novo emprestimo na tabela "emprestimos"
     */
     protected void cadastrarEmprestimo(){
        Emprestimo objEmprestimo = new Emprestimo();
        
        String nome = txtNomeCliente.getText();
        String cpf = txtCpf.getText();
        String nomeJogo = txtNomeJogo.getText();
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataEmp = LocalDate.parse(txtDataEmprestimo.getText(), formatter);
        LocalDate devolucao = LocalDate.parse(txtDevolucao.getText(), formatter);

        
        objEmprestimo.setFkCliente(clienteSelecionado);
        objEmprestimo.setFkJogo(jogoSelecionado);
        objEmprestimo.setNomeCliente(nome);
        objEmprestimo.setCpf(cpf);
        objEmprestimo.setTituloJogo(nomeJogo);
        objEmprestimo.setDataEmp(dataEmp);
        objEmprestimo.setDevolucao(devolucao);
        
        
        EmprestimoDAO emprestimoDAO = new EmprestimoDAO();
        emprestimoDAO.inserir(objEmprestimo);
        
        // Mostra mensagem de Sucesso
        JOptionPane.showMessageDialog(
            this,
            "Cadastro bem-sucedido!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
        
    }


    
     //Metodo usado para pegar o titulo de um Jogo á partir da tabela de Jogos
    protected void pegarDadosJogo() {
    
        
    }

    
    
    
    //Valida se os campos não estão vazios e no formato correto
    private void validarCampos() throws Exception {
        String nomeCliente = txtNomeCliente.getText();
        String cpf = txtCpf.getText();
        String nomeJogo = txtNomeJogo.getText();
        String dataEmpTexto = txtDataEmprestimo.getText().trim();
        String devolucaoTexto = txtDevolucao.getText().trim();
        
       
        
        
        
        //NOME DO CLIENTE
        //Nome do cliente não pode estar vazio
        if (nomeCliente.isEmpty()){
            throw new Exception ("Campo Nome do cliente não pode estar vazio.");
        }
        
        
        //CPF
        //CPF não pode estar vazio
        if (cpf.isEmpty()) {
            throw new Exception ("CPF não pode ser vazio.");
        }
        
        
        //NOME DE JOGO
        //Nome de jogo não pode estar vazio
        if (nomeJogo.isEmpty()){
           throw new Exception ("Campo Nome do jogo aceita somente letras.");
        }
       
        
        //DATA DE EMPRÉSTIMO
        //Data de empréstimo não pode estar vazio
        if (dataEmpTexto.isEmpty()){
           throw new Exception ("Campo Data do empréstimo não pode estar vazio.");
        }
        
        // Data de empréstimo precisa estar no formato DD/MM/AAAA
        if (!dataEmpTexto.matches("\\d{2}/\\d{2}/\\d{4}")) {
        throw new Exception("Data de empréstimo deve estar no formato DD/MM/AAAA. EX: 01/01/2000");
        }
        
        //Data de empréstimo precisa existir no calendário
        try {
        LocalDate.parse(dataEmpTexto, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        }catch (Exception e) {
        throw new Exception("Data de empréstimo inexistente no calendário");
        }
        
        
        //DATA DEVOLUÇÃO
        //Data devolução não pode estar vazio
        if (devolucaoTexto.isEmpty()) {
        throw new Exception("Campo Data de Devolução não pode estar vazio.");
        }
        
        // Data devolução precisa estar no formato DD/MM/AAAA
        if (!devolucaoTexto.matches("\\d{2}/\\d{2}/\\d{4}")) {
        throw new Exception("Data de devolução deve estar no formato DD/MM/AAAA. EX: 01/01/2025");
        }
        
        //Data devolução precisa existir no calendário
        try {
        LocalDate.parse(devolucaoTexto, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } catch (Exception e) {
        throw new Exception("Data de devolução inexistente no calendário.");
        }
        }
    
    
    // Mapeia os atalhos para a tela
    private void mapearTeclas(){
        
        
        // Alt + 1
        lblNomeCliente.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblCpf.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblNomeJogo.setDisplayedMnemonic(KeyEvent.VK_3);

        // Alt + 4
        lblDataEmprestimo.setDisplayedMnemonic(KeyEvent.VK_4); 
        
        // Alt + 5
        lblDevolucao.setDisplayedMnemonic(KeyEvent.VK_5);   
        
        // Alt + C
        btnCadastrar.setMnemonic(KeyEvent.VK_C);
                
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);
        
    }

}



