package view;

import dao.JogoDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Jogo;

/**
 * JFrame usada para cadastrar um novo jogo
 * @author guise
 */
public class CadastroJogo extends javax.swing.JFrame {

   
   
   
   public CadastroJogo() {
        initComponents();
        mapearTeclas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        lblPlataforma = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txtPlataforma = new javax.swing.JTextField();
        lblLancamento = new javax.swing.JLabel();
        txtLancamento = new javax.swing.JTextField();
        lblDesenvolvedora = new javax.swing.JLabel();
        txtDesenvolvedora = new javax.swing.JTextField();
        txtCopias = new javax.swing.JTextField();
        lblCopias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de jogos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N
        jLayeredPane1.setToolTipText("Insira os dados do jogo");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo.setLabelFor(txtTitulo);
        lblTitulo.setText("Título:");
        lblTitulo.setToolTipText("Insira titulo do jogo (Alt + 1)");
        lblTitulo.setNextFocusableComponent(txtGenero);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTitulo.setToolTipText("Insira o titulo do jogo (Alt + 1)");

        txtGenero.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtGenero.setToolTipText("Insira o genêro (Alt + 2)");
        txtGenero.setNextFocusableComponent(txtPlataforma);

        lblPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPlataforma.setLabelFor(txtPlataforma);
        lblPlataforma.setText("Plataforma:");
        lblPlataforma.setToolTipText("");

        lblGenero.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGenero.setLabelFor(txtGenero);
        lblGenero.setText("Genêro:");

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique para voltar ao menu principal (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtTitulo);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(9, 132, 127));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Clique para cadastrar jogo (Alt + C)");
        btnCadastrar.setNextFocusableComponent(btnVoltar);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPlataforma.setToolTipText("Insira o nome da plataforma (Alt + 3)");
        txtPlataforma.setNextFocusableComponent(txtLancamento);

        lblLancamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblLancamento.setLabelFor(txtLancamento);
        lblLancamento.setText("Ano de lançamento:");

        txtLancamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLancamento.setToolTipText("Insira o ano de lançamento (Alt + 4)");
        txtLancamento.setNextFocusableComponent(txtDesenvolvedora);

        lblDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDesenvolvedora.setLabelFor(txtDesenvolvedora);
        lblDesenvolvedora.setText("Desenvolvedora:");

        txtDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesenvolvedora.setToolTipText("Insira o nome da desenvolvedora (Alt + 5)");
        txtDesenvolvedora.setNextFocusableComponent(txtCopias);

        txtCopias.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCopias.setToolTipText("Insira o númro de cópias (Alt + 6)");
        txtCopias.setNextFocusableComponent(btnCadastrar);

        lblCopias.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCopias.setLabelFor(txtCopias);
        lblCopias.setText("Cópias:");

        jLayeredPane1.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtGenero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPlataforma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblGenero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPlataforma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblLancamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtLancamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDesenvolvedora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDesenvolvedora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCopias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCopias, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblPlataforma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblLancamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(lblCopias)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCopias, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(lblDesenvolvedora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlataforma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLancamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesenvolvedora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCopias))
                .addGap(41, 41, 41)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTitulo.getAccessibleContext().setAccessibleName("Campo Titulo");
        txtTitulo.getAccessibleContext().setAccessibleDescription("Campo para inserir o titulo do jogo");
        txtGenero.getAccessibleContext().setAccessibleName("Campo Genêro");
        txtGenero.getAccessibleContext().setAccessibleDescription("Campo para inserir o genêro");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar ao menu principal");
        btnCadastrar.getAccessibleContext().setAccessibleName("Botão Cadastrar");
        btnCadastrar.getAccessibleContext().setAccessibleDescription("Botão para cadastrar o jogo");
        txtPlataforma.getAccessibleContext().setAccessibleName("Campo Plataforma");
        txtPlataforma.getAccessibleContext().setAccessibleDescription("Campo para inserir o nome da plataforma");
        txtLancamento.getAccessibleContext().setAccessibleName("Campo Ano de lançamento");
        txtLancamento.getAccessibleContext().setAccessibleDescription("Campo para inserir o ano de lançamento do jogo");
        txtDesenvolvedora.getAccessibleContext().setAccessibleName("Campo Desenvolvedora");
        txtDesenvolvedora.getAccessibleContext().setAccessibleDescription("Campo  para inserir o nome da desenvolvedora");
        txtCopias.getAccessibleContext().setAccessibleName("Campo Cópias");
        txtCopias.getAccessibleContext().setAccessibleDescription("Campo para inserir o número de cópias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /** 
         * Volta ao MenuPrincipal
         * @param evt 
         */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed
       /**
        * Cadastra um novo jogo
        * @param evt 
        */ 
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            validarCampos();
            cadastrarJogo();     
        dispose();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }              
    }//GEN-LAST:event_btnCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblCopias;
    private javax.swing.JLabel lblDesenvolvedora;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblLancamento;
    private javax.swing.JLabel lblPlataforma;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCopias;
    private javax.swing.JTextField txtDesenvolvedora;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtLancamento;
    private javax.swing.JTextField txtPlataforma;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables


// Métodos usados por esta JFrame
      
    
    /**
     * Cadastra um novo jogo na tabela "jogos"
     */ 
    protected void cadastrarJogo(){
        Jogo objJogo = new Jogo();
        
        String titulo = txtTitulo.getText();
        String genero = txtGenero.getText();
        String plataforma = txtPlataforma.getText();
        int lancamento = Integer.parseInt(txtLancamento.getText());
        String desenvolvedora = txtDesenvolvedora.getText();
        int copias = Integer.parseInt(txtCopias.getText());
        
        
        objJogo.setTitulo(titulo);
        objJogo.setGenero(genero);
        objJogo.setPlataforma(plataforma);
        objJogo.setLancamento(lancamento);
        objJogo.setDesenvolvedora(desenvolvedora);
        objJogo.setCopias(copias);
        
        JogoDAO jogoDAO = new JogoDAO();
        jogoDAO.inserir(objJogo);
        
        // Mostra mensagem de Sucesso
        JOptionPane.showMessageDialog(
            this,
            "Cadastro bem-sucedido!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
   
    }
    
    
    /**
     * Valida se os campos não estão vazios e no formato correto
     * @throws java.lang.Exception
     */ 
        protected void validarCampos() throws Exception {
            String titulo = txtTitulo.getText();
            String genero = txtGenero.getText();
            String plataforma = txtPlataforma.getText();
            String lancamentoTexto = txtLancamento.getText().trim();
            String desenvolvedora = txtDesenvolvedora.getText();
            String copiasTexto = txtCopias.getText();
        
        
        //TITULO
        //Titulo não pode estar vazio
        if (titulo.isEmpty()){
            throw new Exception ("Campo Titulo não pode ser vazio.");
        }
        
        
        //GENERO
        //Genero não pode estar vazio
        if (genero.isEmpty()) {
            throw new Exception ("Genero não pode ser vazio.");
        }
        
        //Genero aceita somente letras
        if (genero.matches("^[0-9]+$")){
           throw new Exception ("Genero aceita somente letras.");
        }
       
        
        //PLATAFORMA
        //Plataforma não pode estar vazio
        if(plataforma.isEmpty()){
           throw new Exception ("Plataforma não pode ser vazio.");
        }
        
        
        //ANO DE LANÇAMENTO
        //Lancamento não pode estar vazio
         if(lancamentoTexto.isEmpty()){
           throw new Exception ("Ano de lançamento não pode ser vazio.");
        }
        
        //Lancamento deve ter exatamento 4 números
        if (!lancamentoTexto.matches("^\\d{4}$")) {
            throw new Exception("Ano de lançamento deve ter exatamente 4 números,EX: 2025");
        }

        // Converte para int
        int lancamentoInt = Integer.parseInt(lancamentoTexto);

        // Verifica se é maior que zero
        if (lancamentoInt <= 0) {
             throw new Exception("Ano de lançamento deve ser maior que zero.");
        }

        
        //DESENVOLVEDORA
        //Desenvolvedora não pode estar vazio
        if(desenvolvedora.isEmpty()){
           throw new Exception ("Desenvolvedora não pode ser vazio.");
        }
        
        
        //COPIAS
        // Copias não pode estar vazio
        if(copiasTexto.isEmpty()){
           throw new Exception ("Cópias não pode ser vazio.");
        }
        
        //Copias aceita somente  números
        if(!copiasTexto.matches("^[0-9]+$")){
           throw new Exception ("Cópias deve conter somente números.");
        }
        
        // Converte para int
        int copiasInt = Integer.parseInt(copiasTexto);

        // Verifica se é maior que zero
        if (copiasInt <= 0) {
            throw new Exception("Copias deve ser maior que zero.");
        }
    }

    
    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblTitulo.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblGenero.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblPlataforma.setDisplayedMnemonic(KeyEvent.VK_3);

        // Alt + 4
        lblLancamento.setDisplayedMnemonic(KeyEvent.VK_4); 
        
        // Alt + 5
        lblDesenvolvedora.setDisplayedMnemonic(KeyEvent.VK_5);   
        
        // Alt + 6
        lblCopias.setDisplayedMnemonic(KeyEvent.VK_6);
        
         // Alt + C
        btnCadastrar.setMnemonic(KeyEvent.VK_C);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);
        
    }
}
