package view;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.Set;
import model.Usuario;
import utilidades.GuardarUsuario;
import utilidades.BackupUtil;


/**
 *
 * @author guise
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    //Mostra uma mensagem de acordo com o usuário que está conectado
    private boolean mostrarMensagem = false;
    
    public MenuPrincipal() {
                    
               
        initComponents();
        mapearTeclas();
        
        
        //Necessário para que a mensagem apareça somente quando ESTA tela for aberta
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowOpened(java.awt.event.WindowEvent e) {
            if (!mostrarMensagem) {
                verificarUsuario(); // mostra a mensagem apenas na primeira vez
                mostrarMensagem = true;
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        cbxJogos = new javax.swing.JComboBox<>();
        lblJogos = new javax.swing.JLabel();
        cbxUsuarios = new javax.swing.JComboBox<>();
        lblUsuarios = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        cbxClientes = new javax.swing.JComboBox<>();
        cbxEmprestimos = new javax.swing.JComboBox<>();
        lblEmprestimos = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblInstrução = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        cbxBackups = new javax.swing.JComboBox<>();
        lblBackups = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLayeredPane1.setToolTipText("Selecione uma opção ou feche o programa");

        cbxJogos.setBackground(new java.awt.Color(0, 102, 102));
        cbxJogos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxJogos.setForeground(new java.awt.Color(255, 255, 255));
        cbxJogos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cadastrar jogo", "Busca de jogo" }));
        cbxJogos.setToolTipText("Cadastrar jogo ou Busca de jogo (Alt + 2)");
        cbxJogos.setNextFocusableComponent(cbxClientes);
        cbxJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJogosActionPerformed(evt);
            }
        });

        lblJogos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblJogos.setLabelFor(cbxJogos);
        lblJogos.setText("Jogos");
        lblJogos.setNextFocusableComponent(cbxClientes);

        cbxUsuarios.setBackground(new java.awt.Color(0, 102, 102));
        cbxUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        cbxUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cadastrar usuário", "Busca de usuário" }));
        cbxUsuarios.setToolTipText("Cadastrar usuário ou Busca de usuário Alt + 1)");
        cbxUsuarios.setNextFocusableComponent(cbxJogos);
        cbxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUsuariosActionPerformed(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsuarios.setLabelFor(cbxUsuarios);
        lblUsuarios.setText("Usuários");

        lblClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblClientes.setLabelFor(cbxClientes);
        lblClientes.setText("Clientes");

        cbxClientes.setBackground(new java.awt.Color(0, 102, 102));
        cbxClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxClientes.setForeground(new java.awt.Color(255, 255, 255));
        cbxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cadastrar cliente", "Busca de cliente" }));
        cbxClientes.setToolTipText("Cadastrar cliente ou Busca de cliente (Alt + 3)");
        cbxClientes.setNextFocusableComponent(cbxEmprestimos);
        cbxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClientesActionPerformed(evt);
            }
        });

        cbxEmprestimos.setBackground(new java.awt.Color(0, 102, 102));
        cbxEmprestimos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEmprestimos.setForeground(new java.awt.Color(255, 255, 255));
        cbxEmprestimos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cadastrar empréstimo", "Busca de empréstimo" }));
        cbxEmprestimos.setToolTipText("Cadastrar empréstimo ou Busca de empréstimo");
        cbxEmprestimos.setNextFocusableComponent(btnFechar);
        cbxEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEmprestimosActionPerformed(evt);
            }
        });

        lblEmprestimos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmprestimos.setLabelFor(cbxEmprestimos);
        lblEmprestimos.setText("Empréstimos");

        lblBemVindo.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(0, 162, 155));
        lblBemVindo.setText("Bem-vindo(a),");

        lblInstrução.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInstrução.setText("Selecione um menu acima para começar.");

        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(0, 162, 155));
        btnFechar.setText("Fechar Programa");
        btnFechar.setToolTipText("botão para fechar o programa (Alt + F)");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        cbxBackups.setBackground(new java.awt.Color(0, 102, 102));
        cbxBackups.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxBackups.setForeground(new java.awt.Color(255, 255, 255));
        cbxBackups.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Criar Backup", "Recuperar Backup" }));
        cbxBackups.setToolTipText("Criar Backup ou Recuperar Backup");
        cbxBackups.setNextFocusableComponent(btnFechar);
        cbxBackups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBackupsActionPerformed(evt);
            }
        });

        lblBackups.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBackups.setLabelFor(cbxEmprestimos);
        lblBackups.setText("Backups");

        jLayeredPane1.setLayer(cbxJogos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblJogos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxEmprestimos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblEmprestimos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblBemVindo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblInstrução, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnFechar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxBackups, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblBackups, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblInstrução)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(lblBemVindo)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblUsuarios))
                                    .addComponent(cbxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(lblJogos)
                                        .addGap(52, 52, 52)
                                        .addComponent(lblClientes))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmprestimos)
                                    .addComponent(cbxEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxBackups, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblBackups)
                                .addGap(27, 27, 27))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJogos)
                            .addComponent(lblClientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxJogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblBackups)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxBackups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblEmprestimos)
                        .addGap(32, 32, 32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(lblBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstrução)
                .addGap(176, 176, 176)
                .addComponent(btnFechar))
        );

        cbxJogos.getAccessibleContext().setAccessibleName("ComboxBox Jogos");
        cbxJogos.getAccessibleContext().setAccessibleDescription("Escolha entre Cadastro de Jogo ou Busca de Jogo");
        cbxUsuarios.getAccessibleContext().setAccessibleName("ComboBox Usuarios");
        cbxUsuarios.getAccessibleContext().setAccessibleDescription("Escolha entre Cadastro de Usuário ou Busca de usuário");
        cbxClientes.getAccessibleContext().setAccessibleName("ComboBox Clientes");
        cbxClientes.getAccessibleContext().setAccessibleDescription("Escolha entre Cadastro de cliente ou Busca de Cliente ");
        cbxEmprestimos.getAccessibleContext().setAccessibleName("ComboBox Empréstimos");
        cbxEmprestimos.getAccessibleContext().setAccessibleDescription("Escolha entre Cadastro de empréstimo ou Busca empréstimo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.getAccessibleContext().setAccessibleName("Menu Principal");

        pack();
    }// </editor-fold>//GEN-END:initComponents
         /**
          * ComboBox para abrir a tela CadastroUsuario ou BuscaUsuario
          */ 
    private void cbxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUsuariosActionPerformed
         int opcao = cbxUsuarios.getSelectedIndex();
        
        // Se "Cadastrar usuário" for selecionado, abre a tela CadastroUsuario
        if (opcao == 1 ){
            
         CadastroUsuario telaCadastroUsuario = new CadastroUsuario();
         telaCadastroUsuario.setVisible(true);      
        }
        
        // Se "Busca de usuario" for selecionado, abre a tela BuscaUsuario
        else if (opcao == 2 ){
            
         BuscaUsuario telaBuscaUsuario = new BuscaUsuario();
         telaBuscaUsuario.setVisible(true);   
        }       
    }//GEN-LAST:event_cbxUsuariosActionPerformed
          /**
           * ComboBox para abrir a tela de Cadastro de Jogo ou Busca de Jogo
           */ 
    private void cbxJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJogosActionPerformed
        int opcao = cbxJogos.getSelectedIndex();
        
        //Se "Cadastrar jogo" for selecionado, abre a tela CadastroJogo
        if (opcao == 1 ){
            
         CadastroJogo telaCadastroJogo = new CadastroJogo();
         telaCadastroJogo.setVisible(true);
        }
        
         // Se "Busca jogo " for selecionado, abre a tela BuscaJogo
        else if (opcao == 2 ){
            
            BuscaJogo telaBuscaJogo = new BuscaJogo();
            telaBuscaJogo.setVisible(true);
          
        }
        
        
        
    }//GEN-LAST:event_cbxJogosActionPerformed
        /**
        * ComboBox para abrir a tela Cadastro de Cliente ou Busca de Cliente
        */ 
    private void cbxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClientesActionPerformed
        int opcao = cbxClientes.getSelectedIndex();
        
        // Se "Cadastrar cliente" for selecionado, abre a tela CadastroCliente
        if (opcao == 1){
            
            CadastroCliente telaCadastroCliente = new CadastroCliente();
            telaCadastroCliente.setVisible(true);        
        }
        
        // Se "Busca cliente " for selecionado, abre a tela BuscaCliente
        else if ( opcao == 2) {
            
            BuscaCliente telaBusca = new BuscaCliente();
            telaBusca.setVisible(true); 
        }
            
    }//GEN-LAST:event_cbxClientesActionPerformed
        /**
         * ComboBox para abrir a tela CadastroEmprestimo ou BuscaEmprestimo
         */ 
    private void cbxEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEmprestimosActionPerformed
        int opcao = cbxEmprestimos.getSelectedIndex();
        
        if (opcao == 1){
            
           CadastroEmprestimo telaCadastroEmprestimo = new CadastroEmprestimo();
           telaCadastroEmprestimo.setVisible(true);       
        }
        
         // Se "Busca empréstimo " for selecionado, abre a tela BuscaEmprestimo
        else if ( opcao == 2) {
            
            BuscaEmprestimo telaBusca = new BuscaEmprestimo();
            telaBusca.setVisible(true); 
           
        }
    }//GEN-LAST:event_cbxEmprestimosActionPerformed
    /**
     * Fecha todo o programa
     */ 
    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja fechar o programa?",
        "Confirmação de encerramento",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
        
        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnFecharActionPerformed
         /**
         * ComboBox para escolher entre criar um backup ou recuperar um backup
         */
    private void cbxBackupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBackupsActionPerformed
        int opcao = cbxBackups.getSelectedIndex();
        BackupUtil backupUtil = new BackupUtil();

        //É necessário executar esse métodos "no fundo" da interface, para evitar congelamentos.

        // Criar backup
        if (opcao == 1) {

            new javax.swing.SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() {
                    backupUtil.criarBackup();
                    return null;
                }
            }.execute();
        }

        // Recuperar backup
        else if (opcao == 2) {

            new javax.swing.SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() {
                    backupUtil.recuperarBackup();
                    return null;
                }
            }.execute();
        }
    }//GEN-LAST:event_cbxBackupsActionPerformed
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JComboBox<String> cbxBackups;
    private javax.swing.JComboBox<String> cbxClientes;
    private javax.swing.JComboBox<String> cbxEmprestimos;
    private javax.swing.JComboBox<String> cbxJogos;
    private javax.swing.JComboBox<String> cbxUsuarios;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBackups;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblEmprestimos;
    private javax.swing.JLabel lblInstrução;
    private javax.swing.JLabel lblJogos;
    private javax.swing.JLabel lblUsuarios;
    // End of variables declaration//GEN-END:variables

//Métodos usados
    
    /**
     * Vai restringir o acesso aos botãos, dependendo do tipo de usuário
     */ 
    protected void verificarUsuario(){
        Usuario user = GuardarUsuario.getUsuario();
        String usuarioLogado = user.getTipoUsuario();
        
        switch (usuarioLogado){
            case "Atendente": //Atendente
                
                cbxUsuarios.setEnabled(false);
                desabilitarOpcoes(cbxJogos, Set.of(1));
                JOptionPane.showMessageDialog(this, "Acesso Restringido. Este tipo de usuário não terá acesso a todas as funções.\n" 
                                                  + "Para mudar isso, escolha o tipo de usuário (Gerente).");   
            break;
            
            case "Estoquista":
                
               cbxClientes.setEnabled(false);
               cbxEmprestimos.setEnabled(false);
               cbxUsuarios.setEnabled(false);
               cbxBackups.setEnabled(false);
               JOptionPane.showMessageDialog(this, "Acesso Restringido. Este tipo de usuário não terá acesso a todas as funções.\n" 
                                                  + "Para mudar isso, escolha o tipo de usuário (Gerente).");
               break;
               
            
            case "Gerente":
               break;
            
               
            case "Supervisor":
                
                cbxUsuarios.setEnabled(false);
                cbxBackups.setEnabled(false);
                desabilitarOpcoes(cbxEmprestimos, Set.of(1)); // desabilita "Cadastrar emprestimos"
                desabilitarOpcoes(cbxJogos, Set.of(1));    // desabilita "Cadastrar jogo"
                desabilitarOpcoes(cbxClientes, Set.of(1)); // desabilita "Cadastrar cliente"
                JOptionPane.showMessageDialog(this, "Acesso Restringido. Este tipo de usuário não terá acesso a todas as funções.\n" 
                                                  + "Para mudar isso, escolha o tipo de usuário (Gerente).");
                
               break;
        }
    }

    

    /**
     * Desabilita botões do sistema, de acordo com o tipo de usuário que está conectado
     * @param comboBox
     * @param indicesDesabilitados
     */ 
    protected void desabilitarOpcoes(JComboBox<String> comboBox, Set<Integer> indicesDesabilitados) {
    
    // Customiza o renderizador para mostrar itens desabilitados, mas apenas visualmente
    comboBox.setRenderer(new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(
                JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (indicesDesabilitados.contains(index)) {
                c.setEnabled(false); 
                c.setForeground(Color.GRAY); 
            } else {
                c.setEnabled(true);
                c.setForeground(Color.BLACK);
            }
            return c;
        }
    });

    // Impede a seleção de opções desabilitadas
    comboBox.addActionListener(e -> {
        if (indicesDesabilitados.contains(comboBox.getSelectedIndex())) {
            JOptionPane.showMessageDialog(comboBox, "Acesso Negado a esta opção.");
            comboBox.setSelectedIndex(0); // volta para "Selecione"
        }
    });
}


    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblUsuarios.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblJogos.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblClientes.setDisplayedMnemonic(KeyEvent.VK_3);        
        
        // Alt + 3
        lblEmprestimos.setDisplayedMnemonic(KeyEvent.VK_4); 
        
        // Alt + E
        btnFechar.setMnemonic(KeyEvent.VK_F);
        
    }
}
