package view;

import dao.UsuarioDAO;
import java.awt.event.KeyEvent;
import model.Usuario;
import javax.swing.JOptionPane;
import static utilidades.ChaveCriptografica.getMD5;


/**
 *
 * @author guise
 */
public class PerfilUsuario extends javax.swing.JFrame {

   //Guarda o jogo selecionado na tela de busca
    Usuario usuarioPassado;
    
    public PerfilUsuario(Usuario usuario) {
        this.usuarioPassado = usuario;
        initComponents();
        mapearTeclas();
        
        
        preencherCampos();
        
        // Desabilita o botão de Confirmar por enquanto
       btnConfirmar.setEnabled(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblNomeUsuario = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        lblTipoUsuario = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        cbxTipoUsuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil de usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N

        lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeUsuario.setLabelFor(txtNomeUsuario);
        lblNomeUsuario.setText("Nome de usuário:");

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSenha.setToolTipText("Insira a senha (Alt + 2)");
        txtSenha.setNextFocusableComponent(cbxTipoUsuario);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSenha.setLabelFor(txtSenha);
        lblSenha.setText("Senha:");

        txtNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomeUsuario.setToolTipText("Insira o nome do usuário (Alt + 1)");
        txtNomeUsuario.setNextFocusableComponent(txtSenha);

        lblTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTipoUsuario.setLabelFor(cbxTipoUsuario);
        lblTipoUsuario.setText("Tipo de usuário:");

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique para voltar a tela Busca usuário (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtNomeUsuario);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(202, 18, 21));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Clique para excluir o usuário (Alt + X)");
        btnExcluir.setNextFocusableComponent(btnVoltar);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(9, 132, 127));
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Clique para editar (Alt + E)");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(9, 132, 127));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setToolTipText("Clique para confirmar a edição (Alt + C)");
        btnConfirmar.setNextFocusableComponent(btnExcluir);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        cbxTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Atendente", "Estoquista", "Gerente", "Supervisor" }));
        cbxTipoUsuario.setToolTipText("Selecione o tipo de usuário (Alt + 3)");
        cbxTipoUsuario.setNextFocusableComponent(btnEditar);

        jLayeredPane1.setLayer(lblNomeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNomeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblNomeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnVoltar)
                        .addGap(89, 89, 89)
                        .addComponent(btnEditar)
                        .addGap(45, 45, 45)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir)
                            .addComponent(btnConfirmar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeUsuario)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnVoltar)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18))
        );

        txtSenha.getAccessibleContext().setAccessibleName("Campo Senha");
        txtSenha.getAccessibleContext().setAccessibleDescription("Campo para inserir a senha");
        txtNomeUsuario.getAccessibleContext().setAccessibleName("Campo Nome de usuário");
        txtNomeUsuario.getAccessibleContext().setAccessibleDescription("Campo para inserir o nome do usuário ");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Clique para voltar ao menu principal");
        btnExcluir.getAccessibleContext().setAccessibleName("Botão Excluir");
        btnExcluir.getAccessibleContext().setAccessibleDescription("Clique para excluir o usuário");
        btnEditar.getAccessibleContext().setAccessibleName("Botão Editar");
        btnEditar.getAccessibleContext().setAccessibleDescription("Clique para editar o usuário");
        btnConfirmar.getAccessibleContext().setAccessibleName("Botão Confirmar");
        btnConfirmar.getAccessibleContext().setAccessibleDescription("Clique para confirmar a edição");
        cbxTipoUsuario.getAccessibleContext().setAccessibleName("ComboBox Tipo de usuário");
        cbxTipoUsuario.getAccessibleContext().setAccessibleDescription("Caixa para selecionar o tipo de usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /**
        * Exclui o usuario da tabela e fecha a tela de perfil
        */
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja excluir este usuario?",
        "Confirmação de exclusão",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (resposta == javax.swing.JOptionPane.YES_OPTION) {
    
        excluirUsuario();
        
        dispose(); 
    }
    }//GEN-LAST:event_btnExcluirActionPerformed
       /** 
         * Permite editar os dados do usuario
         * @param evt
         */ 
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnConfirmar.setEnabled(true);
        
        txtNomeUsuario.setEditable(true);
        txtSenha.setEditable(true);
        cbxTipoUsuario.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed
       /**
        * Atualiza as mudanças feitas para o usuario na tabela
        */
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {     
        validarCampos();
        atualizarUsuario();
        btnConfirmar.setEnabled(false);
       
        dispose();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnConfirmarActionPerformed
        /**
        * Fecha a tela de perfil
        * @param evt
        */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        BuscaUsuario tela = new BuscaUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxTipoUsuario;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables

    /**
     * Métodos usados por essa classe
     */
    
    /** 
     * Preenche os campos automaticamente com os dados do usuario
     */
    protected void preencherCampos() {
       txtNomeUsuario.setText(usuarioPassado.getNomeUsuario());
       txtSenha.setText("********");
       cbxTipoUsuario.setSelectedItem(usuarioPassado.getTipoUsuario());
       
       txtNomeUsuario.setEditable(false);
       txtSenha.setEditable(false);
       cbxTipoUsuario.setEnabled(false);     
}   
    
    
    /**
     * Edita os dados do usuario pelos que estão nos campos.
     * Criptografa a senha.
     */
     protected void atualizarUsuario(){
         UsuarioDAO usuarioDAO = new UsuarioDAO();
         String nome = txtNomeUsuario.getText();
         String senha = txtSenha.getText();
         String tipo = cbxTipoUsuario.getSelectedItem().toString();
         
         String senhaCripto = getMD5(senha);
         
         usuarioDAO.editar(usuarioPassado, nome, senhaCripto, tipo);
        
        JOptionPane.showMessageDialog(
            this,
            "Dados editados com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        txtNomeUsuario.setEditable(true);
        txtSenha.setEditable(true);
        cbxTipoUsuario.setEnabled(true);
        
        
    }
     
     
     /**
     * Exclui o usuario da base de dados
     */
     protected void excluirUsuario(){
         UsuarioDAO usuarioDAO = new UsuarioDAO();
         usuarioDAO.excluir(usuarioPassado.getId());
         
         JOptionPane.showMessageDialog(
            this,
            "Dados excluidos com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
     }


    /**
     * Impede que campos vazios sejam aceitos
     * @throws java.lang.Exception
     */ 
    protected void validarCampos() throws Exception {
        
        String nomeUsuario = txtNomeUsuario.getText();
        String senha = txtSenha.getText();
        String tipo = cbxTipoUsuario.getSelectedItem().toString();
        
        
        if (nomeUsuario.isEmpty()){
            throw new Exception ("Campo Nome de usuário não pode ser vazio.");
        }
        
        if (senha.isEmpty()){
            throw new Exception ("Campo Senha não pode ser vazio.");
        }
        
        if (tipo.equals("Selecione")){
            throw new Exception ("Escolha um tipo de usuário.");
        }
    }
    
    
    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblNomeUsuario.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblSenha.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblTipoUsuario.setDisplayedMnemonic(KeyEvent.VK_3);        
        
        // Alt + E
        btnEditar.setMnemonic(KeyEvent.VK_E);
                
        // Alt + C
        btnConfirmar.setMnemonic(KeyEvent.VK_C);
        
        // Alt + X
        btnExcluir.setMnemonic(KeyEvent.VK_X);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);
    }
}
