package view;

import dao.EmprestimoDAO;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import model.Emprestimo;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.Usuario;
import utilidades.GuardarUsuario;

/**
 * JFrame mostra o perfil do emprestimo
 * @author guise
 */


public class PerfilEmprestimo extends javax.swing.JFrame {

    //Guarda o cliente selecionado na tela de busca
    Emprestimo empPassado;
    
    
    public PerfilEmprestimo(Emprestimo emp) {
        this.empPassado = emp;
        initComponents();
        mapearTeclas();
        
        preencherCampos();
        
        verificarUsuario();
       
        // Desabilita o botão de Confirmar por enquanto
        
        btnConfirmar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtDevolucao = new javax.swing.JTextField();
        txtDataEmp = new javax.swing.JTextField();
        lblDataEmprestimo = new javax.swing.JLabel();
        lblDevolucao = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        lblNomeJogo = new javax.swing.JLabel();
        txtNomeJogo = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil do empréstimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N

        txtDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDevolucao.setToolTipText("Insira a data de devolução (Alt + 5)");
        txtDevolucao.setNextFocusableComponent(btnEditar);

        txtDataEmp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDataEmp.setToolTipText("Insira a data do empréstimo (Alt + 4)");
        txtDataEmp.setNextFocusableComponent(txtDevolucao);

        lblDataEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDataEmprestimo.setLabelFor(txtDataEmp);
        lblDataEmprestimo.setText("Data de empréstimo:");

        lblDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDevolucao.setLabelFor(txtDevolucao);
        lblDevolucao.setText("Data de devolução:");

        lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCpf.setLabelFor(txtCpf);
        lblCpf.setText("CPF:");

        lblNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeCliente.setLabelFor(txtNomeCliente);
        lblNomeCliente.setText("Nome do cliente:");

        lblNomeJogo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeJogo.setLabelFor(txtNomeJogo);
        lblNomeJogo.setText("Nome de jogo:");

        txtNomeJogo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomeJogo.setToolTipText("Clique para inserir o nome de um jogo (Alt + 3)");
        txtNomeJogo.setNextFocusableComponent(txtDataEmp);

        txtNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomeCliente.setToolTipText("Clique para inserir  o nome do cliente (Alt + 1)");
        txtNomeCliente.setNextFocusableComponent(txtCpf);

        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCpf.setToolTipText("Clique para inserir o CPF de um cliente (Alt + 2)");
        txtCpf.setNextFocusableComponent(txtNomeJogo);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(9, 132, 127));
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Clique para editar empréstimo (Alt + E)");
        btnEditar.setNextFocusableComponent(btnConfirmar);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique para voltar a tela Busca empréstimo (Alt +V)");
        btnVoltar.setNextFocusableComponent(txtNomeCliente);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(9, 132, 127));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setToolTipText("Clique para confirmar a edição (Alt + C)");
        btnConfirmar.setNextFocusableComponent(btnExcluir);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(202, 18, 21));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Clique para excluir o empréstimo (Alt + X)");
        btnExcluir.setNextFocusableComponent(btnVoltar);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(txtDevolucao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDataEmp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDataEmprestimo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDevolucao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNomeCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNomeJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNomeJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNomeCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(64, 64, 64)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir)
                            .addComponent(btnConfirmar)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblDataEmprestimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblDevolucao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblNomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblNomeJogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeJogo)
                    .addComponent(txtNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataEmprestimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDevolucao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar)
                            .addComponent(btnEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)))
                .addGap(21, 21, 21))
        );

        txtDevolucao.getAccessibleContext().setAccessibleDescription("Campo para inserir a data de devolução");
        txtDataEmp.getAccessibleContext().setAccessibleName("Campo Data de empréstimo");
        txtDataEmp.getAccessibleContext().setAccessibleDescription("Campo para inserir a data do empréstimo");
        txtNomeJogo.getAccessibleContext().setAccessibleName("Campo Nome de jogo");
        txtNomeJogo.getAccessibleContext().setAccessibleDescription("Campo para inserir o nome de um jogo");
        txtNomeCliente.getAccessibleContext().setAccessibleName("Campo Nome do cliente");
        txtNomeCliente.getAccessibleContext().setAccessibleDescription("Campo para inserir  o nome do cliente");
        txtCpf.getAccessibleContext().setAccessibleName("Campo CPF");
        txtCpf.getAccessibleContext().setAccessibleDescription("Campo para inserir o CPF de um cliente");
        btnEditar.getAccessibleContext().setAccessibleName("Botão Editar");
        btnEditar.getAccessibleContext().setAccessibleDescription("Botão para editar o empréstimo");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar ao menu principal");
        btnConfirmar.getAccessibleContext().setAccessibleName("Botão Confirmar");
        btnConfirmar.getAccessibleContext().setAccessibleDescription("Botão para confirmar a edição do empréstimo");
        btnExcluir.getAccessibleContext().setAccessibleName("Botão Excluir");
        btnExcluir.getAccessibleContext().setAccessibleDescription("Botão para excluir o empréstimo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /**
         * Fecha a tela de perfil
         */ 
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        BuscaEmprestimo tela = new BuscaEmprestimo();
        tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed
        /**
        * Exclui o emprestimo da tabela e fecha a tela de perfil
        */
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja excluir este emprestimo?",
        "Confirmação de exclusão",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (resposta == javax.swing.JOptionPane.YES_OPTION) {
       excluirEmprestimo();
        
        dispose(); 
    }
    }//GEN-LAST:event_btnExcluirActionPerformed
         /**
          * Permite editar os dados do jogo
          */ 
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnConfirmar.setEnabled(true);
        
        txtNomeCliente.setEditable(true);
        txtCpf.setEditable(true);
        txtNomeJogo.setEditable(true);
        txtDataEmp.setEditable(true);
        txtDevolucao.setEditable(true);
    }//GEN-LAST:event_btnEditarActionPerformed
        /**
         * Atualiza as mudanças feitas para o empréstimo na tabela
         */ 
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
        validarCampos();
        atualizarEmprestimo();
        btnConfirmar.setEnabled(false);
     
        dispose();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataEmprestimo;
    private javax.swing.JLabel lblDevolucao;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeJogo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataEmp;
    private javax.swing.JTextField txtDevolucao;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeJogo;
    // End of variables declaration//GEN-END:variables

//Métodos usados
    
    protected void preencherCampos(){
        // Cria um formatador no padrão brasileiro (dia/mês/ano)
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
        txtNomeCliente.setText(empPassado.getNomeCliente());
        txtCpf.setText(empPassado.getCpf());
        txtNomeJogo.setText(empPassado.getTituloJogo());
        txtDataEmp.setText(empPassado.getDataEmp().format(formatter));
        txtDevolucao.setText(empPassado.getDevolucao().format(formatter));
    
        txtNomeCliente.setEditable(false);
        txtCpf.setEditable(false);
        txtNomeJogo.setEditable(false);
        txtDataEmp.setEditable(false);
        txtDevolucao.setEditable(false);
    }
    
    //Edita os dados do emprestimo de acordo com o que está nos campos
    private void atualizarEmprestimo(){
        EmprestimoDAO empDAO = new EmprestimoDAO();
        
        String nome = txtNomeCliente.getText();
        String cpf = txtCpf.getText();
        String titulo = txtNomeJogo.getText();
        
        // Converte as strings dos campos para LocalDate
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataEmp = LocalDate.parse(txtDataEmp.getText(), formatter);
        LocalDate devolucao = LocalDate.parse(txtDevolucao.getText(), formatter);
        
        empDAO.editar(empPassado, nome, cpf, titulo, dataEmp, devolucao);
        
        JOptionPane.showMessageDialog(
            this,
            "Dados editados com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        txtNomeCliente.setEditable(false);
        txtCpf.setEditable(false);
        txtNomeJogo.setEditable(false);
        txtDataEmp.setEditable(false);
        txtDevolucao.setEditable(false);
    }
    
    
    /**
     * Exclui o emprestimo da base de dados
     */
     protected void excluirEmprestimo(){
         EmprestimoDAO empDAO = new EmprestimoDAO();
         empDAO.excluir(empPassado.getId());
         
         JOptionPane.showMessageDialog(
            this,
            "Dados excluidos com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
     }
    
    
    /**
     * Vai restringir o acesso aos botões, dependendo do tipo de usuário
     */ 
    protected void verificarUsuario(){
        Usuario user = GuardarUsuario.getUsuario();
        String usuarioLogado = user.getTipoUsuario();
        
        switch (usuarioLogado){
            case "Atendente":
                 //Sem restrições
            break;
            
            case "Estoquista":
               //Nem chega nesta tela
               break;
               
            case "Gerente":
                //Sem restrições
               break;
            
               
            case "Supervisor": 
                 btnConfirmar.setEnabled(false);
                 btnEditar.setEnabled(false);
                 btnExcluir.setEnabled(false);
               break;
        }
    }

    
    /**
     * Valida se os campos não estão vazios e no formato correto
     * @throws java.lang.Exception
     */ 
    protected void validarCampos() throws Exception {
        String nomeCliente = txtNomeCliente.getText();
        String cpf = txtCpf.getText();
        String nomeJogo = txtNomeJogo.getText();
        String dataEmpTexto = txtDataEmp.getText().trim();
        String devolucaoTexto = txtDevolucao.getText().trim();
        
       
        
        
        
        //NOME DO CLIENTE
        //Nome do cliente não pode estar vazio
        if (nomeCliente.isEmpty()){
            throw new Exception ("Campo Nome do cliente não pode estar vazio.");
        }
        
        //Nome aceita apenas letras e nome completo 
        if (!nomeCliente.matches("^[\\p{L} ]+$")){
            throw new Exception ("Campo Nome do cliente deve conter apenas letras e deve ser completo .");
        }
        
        
        //CPF
        //CPF não pode estar vazio
        if (cpf.isEmpty()) {
            throw new Exception ("CPF não pode ser vazio.");
        }
        
        //CPF só aceita números e no formato "000.000.000-00"
        if (!cpf.matches("^\\d{3}\\.\\d{3}\\.\\d{3}[-\\.]\\d{2}$") || !cpf.matches("^[0-9.-]+$")){
            throw new Exception ("CPF aceita somente números e no seguinte formato: 000.000.000-00 ou 000.000.000.00");
        }
        
        
        //NOME DE JOGO
        //Nome de jogo não pode estar vazio
        if (nomeJogo.isEmpty()){
           throw new Exception ("Campo Nome do jogo aceita somente letras.");
        }
       
        
        //DATA DE EMPRÉSTIMO
        //Data de empréstimo não pode estar vazio
        if (dataEmpTexto.isEmpty()){
           throw new Exception ("Campo Data do empréstimo não pode estar vazio.");
        }
        
        // Data de empréstimo precisa estar no formato DD/MM/AAAA
        if (!dataEmpTexto.matches("\\d{2}/\\d{2}/\\d{4}")) {
        throw new Exception("Data de empréstimo deve estar no formato DD/MM/AAAA. EX: 01/01/2000");
        }
        
        //Data de empréstimo precisa existir no calendário
        try {
        LocalDate.parse(dataEmpTexto, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        }catch (Exception e) {
        throw new Exception("Data de empréstimo inexistente no calendário");
        }
        
        
        //DATA DEVOLUÇÃO
        //Data devolução não pode estar vazio
        if (devolucaoTexto.isEmpty()) {
        throw new Exception("Campo Data de Devolução não pode estar vazio.");
        }
        
        // Data devolução precisa estar no formato DD/MM/AAAA
        if (!devolucaoTexto.matches("\\d{2}/\\d{2}/\\d{4}")) {
        throw new Exception("Data de devolução deve estar no formato DD/MM/AAAA. EX: 01/01/2025");
        }
        
        //Data devolução precisa existir no calendário
        try {
        LocalDate.parse(devolucaoTexto, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } catch (Exception e) {
        throw new Exception("Data de devolução inexistente no calendário.");
        }
        }
    
    
    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblNomeCliente.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblCpf.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblNomeJogo.setDisplayedMnemonic(KeyEvent.VK_3);

        // Alt + 4
        lblDataEmprestimo.setDisplayedMnemonic(KeyEvent.VK_4); 
        
        // Alt + 5
        lblDevolucao.setDisplayedMnemonic(KeyEvent.VK_5);   
        
        // Alt + E
        btnEditar.setMnemonic(KeyEvent.VK_E);
                
        // Alt + C
        btnConfirmar.setMnemonic(KeyEvent.VK_C);
        
        // Alt + X
        btnExcluir.setMnemonic(KeyEvent.VK_X);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);
        
    }
}
