package view;

import java.awt.event.KeyEvent;
import model.Cliente;
import dao.ClienteDAO;
import javax.swing.JOptionPane;
import model.Usuario;
import utilidades.GuardarUsuario;

/**
 * JFrame mostra o perfil do cliente
 * @author guise
 */

public class PerfilCliente extends javax.swing.JFrame {

    //Guarda o cliente selecionado na tela de busca
    Cliente clientePassado;
    
    public PerfilCliente(Cliente cliente) {
        this.clientePassado = cliente;
        initComponents();
        
        mapearTeclas();
        preencherCampos();
        verificarUsuario();
        
        // Desabilita o botão de Confirmar por enquanto
        
        btnConfirmar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblDadosPessoais = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtResidencial = new javax.swing.JTextField();
        lblResidencial = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVinculado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil de cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N
        jLayeredPane1.setToolTipText("Insira os dados do cliente");

        lblDadosPessoais.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDadosPessoais.setForeground(new java.awt.Color(51, 0, 153));
        lblDadosPessoais.setText("Dados Pessoais");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNome.setToolTipText("Inserir nome e sobrenome (Alt + 1)");
        txtNome.setNextFocusableComponent(txtCpf);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNome.setLabelFor(txtNome);
        lblNome.setText("Nome e sobrenome:");

        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCpf.setToolTipText("Inserir CPF (Alt + 2)");
        txtCpf.setNextFocusableComponent(txtBairro);

        lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCpf.setLabelFor(txtCpf);
        lblCpf.setText("CPF:");

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(51, 0, 153));
        lblEndereco.setText("Endereço");

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtBairro.setToolTipText("Inserir Bairro (Alt + 3)");
        txtBairro.setNextFocusableComponent(txtRua);

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBairro.setLabelFor(txtBairro);
        lblBairro.setText("Bairro:");

        lblRua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRua.setLabelFor(txtRua);
        lblRua.setText("Rua:");

        txtRua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtRua.setToolTipText("Inserir Rua (Alt + 4)");
        txtRua.setNextFocusableComponent(txtResidencial);

        txtResidencial.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtResidencial.setToolTipText("Inserir Número Residencial (Alt + 5)");
        txtResidencial.setNextFocusableComponent(btnVinculado);

        lblResidencial.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblResidencial.setLabelFor(txtResidencial);
        lblResidencial.setText("N Residencial:");

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(9, 132, 127));
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Editar cliente (Alt + E)");
        btnEditar.setNextFocusableComponent(btnConfirmar);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Voltar para a tela Busca Cliente (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtNome);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(9, 132, 127));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setToolTipText("Confirmar edição (Alt + C)");
        btnConfirmar.setNextFocusableComponent(btnExcluir);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(202, 18, 21));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir cliente (Alt + X)");
        btnExcluir.setNextFocusableComponent(btnVoltar);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVinculado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVinculado.setForeground(new java.awt.Color(9, 132, 127));
        btnVinculado.setText("Ver empréstimos vinculados");
        btnVinculado.setToolTipText("Ver empréstimo vinculados (Alt + 6)");
        btnVinculado.setNextFocusableComponent(btnEditar);
        btnVinculado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVinculadoActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblDadosPessoais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtResidencial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblResidencial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVinculado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(64, 64, 64)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir)
                            .addComponent(btnConfirmar)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblResidencial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEndereco)
                            .addComponent(lblDadosPessoais)
                            .addComponent(btnVinculado))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(lblDadosPessoais)
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(lblEndereco)
                .addGap(34, 34, 34)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResidencial))
                .addGap(31, 31, 31)
                .addComponent(btnVinculado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar)
                            .addComponent(btnEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );

        txtNome.getAccessibleContext().setAccessibleName("Campo Nome e sobrenome:");
        txtNome.getAccessibleContext().setAccessibleDescription("Campo para  inserir nome e sobrenome");
        txtCpf.getAccessibleContext().setAccessibleName("Campo CPF");
        txtCpf.getAccessibleContext().setAccessibleDescription("Campo para inserir CPF ");
        txtBairro.getAccessibleContext().setAccessibleName("Campo Bairro");
        txtBairro.getAccessibleContext().setAccessibleDescription("Campo para  inserir o Bairro");
        txtRua.getAccessibleContext().setAccessibleName("Campo Rua");
        txtRua.getAccessibleContext().setAccessibleDescription("Campo para inserir a Rua");
        txtResidencial.getAccessibleContext().setAccessibleName("Campo N Residencial");
        txtResidencial.getAccessibleContext().setAccessibleDescription("Campo para inserir o Número Residencial");
        btnEditar.getAccessibleContext().setAccessibleName("Botão Editar");
        btnEditar.getAccessibleContext().setAccessibleDescription("Botão para editar o cliente");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar para o menu principal");
        btnConfirmar.getAccessibleContext().setAccessibleName("Botão Confirmar");
        btnConfirmar.getAccessibleContext().setAccessibleDescription("Botão para  confirmar edição");
        btnExcluir.getAccessibleContext().setAccessibleName("Botão Excluir");
        btnExcluir.getAccessibleContext().setAccessibleDescription("Botão para excluir o cliente ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /**
        * Fecha a tela de perfil
        */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        BuscaCliente tela = new BuscaCliente();
        tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed
        /**
        * Exclui o cliente da tabela e fecha a tela de perfil
        */
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja excluir este cliente?\n"
        + "(Todos os empréstimos feitos por este cliente também serão perdidos.)",
        "Confirmação de exclusão",
        javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
        // Remove o jogo da lista principal (armazenada na tela BuscaCliente)
        excluirCliente();
        dispose();
    }
    }//GEN-LAST:event_btnExcluirActionPerformed
        /**
        * Permite editar os dados do cliente
        */ 
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnConfirmar.setEnabled(true);
        
        txtNome.setEditable(true);
        txtCpf.setEditable(true);
        txtBairro.setEditable(true);
        txtRua.setEditable(true);
        txtResidencial.setEditable(true);
    }//GEN-LAST:event_btnEditarActionPerformed
        /**
        * Atualiza as mudanças feitas para o item na tabela
        */ 
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
        validarCampos();
        atualizarCliente();
        btnConfirmar.setEnabled(false);
        } 
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnConfirmarActionPerformed
       // Mostra uma lista com todos os empréstimos feito por este cliente 
    private void btnVinculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVinculadoActionPerformed
            verEmprestimo();
        
        
    }//GEN-LAST:event_btnVinculadoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVinculado;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDadosPessoais;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblResidencial;
    private javax.swing.JLabel lblRua;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtResidencial;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables

    /**
     * Métodos desta JFrame
     */
    
    
    
    /** 
     * Preenche os campos automaticamente com os dados do cliente
     */
    protected void preencherCampos() {
       txtNome.setText(clientePassado.getNome());
       txtCpf.setText(clientePassado.getCpf());
       txtBairro.setText(clientePassado.getBairro());
       txtRua.setText(clientePassado.getRua());
       txtResidencial.setText(String.valueOf(clientePassado.getResidencial()));

    //Deixa os campos bloqueados inicialmente
        txtNome.setEditable(false);
        txtCpf.setEditable(false);
        txtBairro.setEditable(false);
        txtRua.setEditable(false);
        txtResidencial.setEditable(false);
}
    
    /**
     * Edita os dados do cliente pelos que estão nos campos
     */ 
    protected void atualizarCliente(){
        ClienteDAO clienteDAO = new ClienteDAO();
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String bairro = txtBairro.getText();
        String rua = txtRua.getText();
        int residencial = (Integer.parseInt(txtResidencial.getText()));
        
        clienteDAO.editar(clientePassado, nome, cpf, bairro, rua, residencial);
        
        JOptionPane.showMessageDialog(
            this,
            "Dados editados com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        txtNome.setEditable(false);
        txtCpf.setEditable(false);
        txtBairro.setEditable(false);
        txtRua.setEditable(false);
        txtResidencial.setEditable(false);
    }
    
    
    /**
     * Exclui o cliente da base de dados
     */
     protected void excluirCliente(){
         ClienteDAO clienteDAO = new ClienteDAO();
         clienteDAO.excluir(clientePassado.getId());
         
         JOptionPane.showMessageDialog(
            this,
            "Dados excluidos com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
     }
    
     
     /**
      * Abre uma lista de todos os emprestimos feitos por este cliente
      */
     protected void verEmprestimo(){
         EmprestimoVinculado tela = new EmprestimoVinculado(clientePassado);
         tela.setVisible(true);
         
     }
     
     
    /**
     * Vai restringir o acesso aos botões, dependendo do tipo de usuário
     */ 
    protected void verificarUsuario(){
        Usuario user = GuardarUsuario.getUsuario();
        String usuarioLogado = user.getTipoUsuario();
        
        switch (usuarioLogado){
            case "Atendente":
                 //Sem restrições
            break;
            
            case "Estoquista":
               //Nem chega nesta tela
               break;
               
            case "Gerente":
                //Sem restrições
               break;
            
               
            case "Supervisor": 
                 btnConfirmar.setEnabled(false);
                 btnEditar.setEnabled(false);
                 btnExcluir.setEnabled(false);
               break;
        }
    }

    
    /**
     * Valida se os campos não estão vazios e no formato correto
     * @throws java.lang.Exception
     */ 
    protected void validarCampos() throws Exception {
        String nome = txtNome.getText();
        String cpf = txtCpf.getText().trim();
        String bairro = txtBairro.getText();
        String rua = txtRua.getText();
        
        String residencialTexto = txtResidencial.getText().trim();
        
        //NOME
        //Nome e Sobrenome não pode estar vazio
        if (nome.isEmpty()){
            throw new Exception ("Campo Nome e Sobrenome não pode ser vazio.");
        }
        
        //Nome aceita apenas letras e nome completo 
        if (!nome.matches("^[\\p{L} ]+$")){
            throw new Exception ("Campo Nome e Sobrenome deve conter apenas letras e espaços.");
        }
        
        
        // CPF
        //CPF não pode estar vazio
        if (cpf.isEmpty()) {
            throw new Exception ("CPF não pode ser vazio.");
        }
        
        // CPF só aceita números e no formato "000.000.000-00"
        if (!cpf.matches("^\\d{3}\\.\\d{3}\\.\\d{3}[-\\.]\\d{2}$") || !cpf.matches("^[0-9.-]+$")){
            throw new Exception ("CPF aceita somente números e no seguinte formato: 000.000.000-00 ou 000.000.000.00");
        }
        
        
        //BAIRRO
        //Bairro não pode estar vazio
        if(bairro.isEmpty()){
           throw new Exception ("Bairro não pode ser vazio.");
        }
        
        //Bairro aceita somente letras
        if (bairro.matches("^[0-9]+$")){
           throw new Exception ("Bairro aceita somente letras.");
        }
        
        
        //RUA
        //"Rua" não pode estar vazio
        if(rua.isEmpty()){
           throw new Exception ("Rua não pode ser vazio.");
        }
        
        //Rua aceita somente letras
        if (rua.matches("^[0-9]+$")){
           throw new Exception ("Rua aceita somente letras.");
        }
        
        
        //RESIDENCIAL
        // "N Residencial" não pode estar vazio
        if(residencialTexto.isEmpty()){
           throw new Exception ("Nº Residencial não pode ser vazio.");
        }
        
        //"N Residencial" aceita somente  números
        if(!residencialTexto.matches("^[0-9]+$")){
           throw new Exception ("Nº Residencial deve conter apenas números.");
        }
        
        // Converte para int
        int residencialInt = Integer.parseInt(residencialTexto);

        // Verifica se é maior que zero
        if (residencialInt <= 0) {
            throw new Exception("Nº Residencial deve ser maior que zero.");
}
    }
    
    
    /**
    * Mapeia os atalhos para a tela
    */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblNome.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblCpf.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblBairro.setDisplayedMnemonic(KeyEvent.VK_3);

        // Alt + 4
        lblRua.setDisplayedMnemonic(KeyEvent.VK_4); 
        
        // Alt + 5
        lblResidencial.setDisplayedMnemonic(KeyEvent.VK_5);   
        
        // Alt + 6
        btnVinculado.setMnemonic(KeyEvent.VK_6);
                
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);
        
        // Alt + E
        btnEditar.setMnemonic(KeyEvent.VK_E);
                
        // Alt + C
        btnConfirmar.setMnemonic(KeyEvent.VK_C);
        
        // Alt + X
        btnExcluir.setMnemonic(KeyEvent.VK_X);
    }
}
