package view;

import dao.JogoDAO;
import java.awt.event.KeyEvent;
import model.Jogo;
import javax.swing.JOptionPane;
import model.Usuario;
import utilidades.GuardarUsuario;

public class PerfilJogo extends javax.swing.JFrame {
    
    //Guarda o jogo selecionado na tela de busca
    Jogo jogoPassado;
     
    public PerfilJogo(Jogo jogo) {
       this.jogoPassado = jogo;
       initComponents();
       mapearTeclas();
    
       preencherCampos();
       verificarUsuario();
       
       // Desabilita o botão de Confirmar por enquanto
       btnConfirmar.setEnabled(false);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtCopias = new javax.swing.JTextField();
        lblCopias = new javax.swing.JLabel();
        lblDesenvolvedora = new javax.swing.JLabel();
        lblLancamento = new javax.swing.JLabel();
        lblPlataforma = new javax.swing.JLabel();
        txtPlataforma = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtDesenvolvedora = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtLancamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil de jogo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 153))); // NOI18N

        txtCopias.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCopias.setToolTipText("Insira o númro de cópias (Alt + 6)");
        txtCopias.setNextFocusableComponent(btnEditar);

        lblCopias.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCopias.setLabelFor(txtCopias);
        lblCopias.setText("Cópias:");

        lblDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDesenvolvedora.setLabelFor(txtDesenvolvedora);
        lblDesenvolvedora.setText("Desenvolvedora:");

        lblLancamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblLancamento.setLabelFor(txtLancamento);
        lblLancamento.setText("Ano de lançamento:");

        lblPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPlataforma.setLabelFor(txtPlataforma);
        lblPlataforma.setText("Plataforma:");

        txtPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPlataforma.setToolTipText("Insira o nome da plataforma (Alt + 3)");
        txtPlataforma.setNextFocusableComponent(txtLancamento);

        txtGenero.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtGenero.setToolTipText("Insira o genêro (Alt + 2)");
        txtGenero.setNextFocusableComponent(txtPlataforma);

        lblGenero.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGenero.setLabelFor(txtGenero);
        lblGenero.setText("Genêro:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitulo.setLabelFor(txtTitulo);
        lblTitulo.setText("Título:");

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTitulo.setToolTipText("Insira o titulo do jogo (Alt + 1)");
        txtTitulo.setNextFocusableComponent(txtGenero);

        txtDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDesenvolvedora.setToolTipText("Insira o nome da desenvolvedora (Alt + 5)");
        txtDesenvolvedora.setNextFocusableComponent(txtCopias);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(9, 132, 127));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique para voltar a tela Busca Jogo (Alt + V)");
        btnVoltar.setNextFocusableComponent(txtTitulo);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(9, 132, 127));
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Clique para editar o jogo (Alt + E)");
        btnEditar.setNextFocusableComponent(btnConfirmar);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(9, 132, 127));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setToolTipText("Clique para confirmar a edição dos dados (Alt + C)");
        btnConfirmar.setNextFocusableComponent(btnExcluir);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(202, 18, 21));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Clique para excluir o jogo (Alt + X)");
        btnExcluir.setNextFocusableComponent(btnVoltar);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtLancamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLancamento.setToolTipText("Insira o ano de lançamento (Alt + 4)");
        txtLancamento.setNextFocusableComponent(txtDesenvolvedora);

        jLayeredPane1.setLayer(txtCopias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCopias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDesenvolvedora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblLancamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPlataforma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPlataforma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtGenero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblGenero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDesenvolvedora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtLancamento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblPlataforma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblLancamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblDesenvolvedora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblCopias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCopias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(64, 64, 64)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir)
                            .addComponent(btnConfirmar))
                        .addGap(23, 23, 23))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlataforma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLancamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesenvolvedora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCopias)
                    .addComponent(txtCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addComponent(btnEditar))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addContainerGap())
        );

        txtCopias.getAccessibleContext().setAccessibleName("Campo Cópias");
        txtCopias.getAccessibleContext().setAccessibleDescription("Campo para inserir o número de cópias");
        txtPlataforma.getAccessibleContext().setAccessibleName("Campo Plataforma");
        txtPlataforma.getAccessibleContext().setAccessibleDescription("Campo para inserir o nome da plataforma");
        txtGenero.getAccessibleContext().setAccessibleName("Campo Genêro");
        txtGenero.getAccessibleContext().setAccessibleDescription("Campo para inserir o genêro");
        txtTitulo.getAccessibleContext().setAccessibleName("Campo Título");
        txtTitulo.getAccessibleContext().setAccessibleDescription("Campor para inserir o titulo do jogo");
        txtDesenvolvedora.getAccessibleContext().setAccessibleName("Campo Desenvolvedora");
        txtDesenvolvedora.getAccessibleContext().setAccessibleDescription("Campo  para inserir o nome da desenvolvedora");
        btnVoltar.getAccessibleContext().setAccessibleName("Botão Voltar");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar ao menu principal");
        btnEditar.getAccessibleContext().setAccessibleName("Botão Editar");
        btnEditar.getAccessibleContext().setAccessibleDescription("Botão para editar o jogo");
        btnConfirmar.getAccessibleContext().setAccessibleName("Botão Confirmar");
        btnConfirmar.getAccessibleContext().setAccessibleDescription("Botão para confirmar a edição do jogo");
        btnExcluir.getAccessibleContext().setAccessibleName("Botão Excluir");
        btnExcluir.getAccessibleContext().setAccessibleDescription("Botão para excluir o jogo");
        txtLancamento.getAccessibleContext().setAccessibleName("Campo Ano de lançamento");
        txtLancamento.getAccessibleContext().setAccessibleDescription("Campo para inserir o ano de lançamento do jogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       /**
        * Fecha a tela de perfil():
        * @param evt
        */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        BuscaJogo tela = new BuscaJogo();
        tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed
        /**
        * Exclui o usuario da tabela e fecha a tela de perfil
        */
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja excluir este jogo?\n"
        + "(Todos os empréstimos feitos com este jogo também serão perdidos.)",
        "Confirmação de exclusão",
        javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (resposta == javax.swing.JOptionPane.YES_OPTION) {   
        excluirJogo();
        dispose();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
        /** 
         * Permite editar os dados do jogo
         * @param evt
         */ 
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnConfirmar.setEnabled(true);
        
        txtTitulo.setEditable(true);
        txtGenero.setEditable(true);
        txtPlataforma.setEditable(true);
        txtLancamento.setEditable(true);
        txtDesenvolvedora.setEditable(true);
        txtCopias.setEditable(true);
    }//GEN-LAST:event_btnEditarActionPerformed
       /**
        * Atualiza as mudanças feitas para o jogo na tabela
        */ 
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
        validarCampos();
        atualizarJogo();
        btnConfirmar.setEnabled(false);
        } 
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblCopias;
    private javax.swing.JLabel lblDesenvolvedora;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblLancamento;
    private javax.swing.JLabel lblPlataforma;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCopias;
    private javax.swing.JTextField txtDesenvolvedora;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtLancamento;
    private javax.swing.JTextField txtPlataforma;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
    
    // Métodos usados
    
  
    /** 
     * Preenche os campos automaticamente com os dados do jogo
     */
    protected void preencherCampos() {
       txtTitulo.setText(jogoPassado.getTitulo());
       txtGenero.setText(jogoPassado.getGenero());
       txtPlataforma.setText(jogoPassado.getPlataforma());
       txtLancamento.setText(String.valueOf(jogoPassado.getLancamento()));
       txtDesenvolvedora.setText(jogoPassado.getDesenvolvedora());
       txtCopias.setText(String.valueOf(jogoPassado.getCopias()));

        //Deixa os campos bloqueados inicialmente
        txtTitulo.setEditable(false);
        txtGenero.setEditable(false);
        txtPlataforma.setEditable(false);
        txtLancamento.setEditable(false);
        txtDesenvolvedora.setEditable(false);
        txtCopias.setEditable(false); 
}   
    
    
    /**
     * Edita os dados do jogo pelos que estão nos campos
     */
     protected void atualizarJogo(){
         JogoDAO jogoDAO = new JogoDAO();
         String titulo = txtTitulo.getText();
         String genero = txtGenero.getText();
         String plataforma = txtPlataforma.getText();
         int lancamento = Integer.parseInt(txtLancamento.getText());
         String desenvolvedora = txtDesenvolvedora.getText();
         int copias = Integer.parseInt(txtCopias.getText());
         
         jogoDAO.editar(jogoPassado, titulo, genero, plataforma, lancamento, desenvolvedora, copias);
        
        JOptionPane.showMessageDialog(
            this,
            "Dados editados com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        txtTitulo.setEditable(false);
        txtGenero.setEditable(false);
        txtPlataforma.setEditable(false);
        txtLancamento.setEditable(false);
        txtDesenvolvedora.setEditable(false);
        txtCopias.setEditable(false);
    }
     
     
     /**
     * Exclui o jogo da base de dados
     */
     protected void excluirJogo(){
         JogoDAO jogoDAO = new JogoDAO();
         jogoDAO.excluir(jogoPassado.getId());
         
         JOptionPane.showMessageDialog(
            this,
            "Dados excluidos com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );
     }

    
    /**
     * Vai restringir o acesso aos botões, dependendo do tipo de usuário
     */ 
    protected void verificarUsuario(){
        Usuario user = GuardarUsuario.getUsuario();
        String usuarioLogado = user.getTipoUsuario();
        
        switch (usuarioLogado){
            case "Atendente":
               btnConfirmar.setEnabled(false);
               btnEditar.setEnabled(false);
               btnExcluir.setEnabled(false);
            break;
            
            case "Estoquista":
               //Sem restrições
               break;
               
            case "Gerente":
                //Sem restrições
               break;
            
               
            case "Supervisor": 
                 btnConfirmar.setEnabled(false);
                 btnEditar.setEnabled(false);
                 btnExcluir.setEnabled(false);
               break;
        }
    }
    
    
    /**
     * Valida se os campos não estão vazios e no formato correto
     * @throws java.lang.Exception
     */ 
    protected void validarCampos() throws Exception {
        String titulo = txtTitulo.getText();
        String genero = txtGenero.getText();
        String plataforma = txtPlataforma.getText();
        String lancamentoTexto = txtLancamento.getText().trim();
        String desenvolvedora = txtDesenvolvedora.getText();
        String copiasTexto = txtCopias.getText();
        
        
        //TITULO
        //Titulo não pode estar vazio
        if (titulo.isEmpty()){
            throw new Exception ("Campo Titulo não pode ser vazio.");
        }
        
        
        //GENERO
        //Genero não pode estar vazio
        if (genero.isEmpty()) {
            throw new Exception ("Genero não pode ser vazio.");
        }
        
        //Genero aceita somente letras
        if (genero.matches("^[0-9]+$")){
           throw new Exception ("Genero aceita somente letras.");
        }
       
        
        //PLATAFORMA
        //Plataforma não pode estar vazio
        if(plataforma.isEmpty()){
           throw new Exception ("Plataforma não pode ser vazio.");
        }
        
        
        //ANO DE LANÇAMENTO
        //Lancamento não pode estar vazio
         if(lancamentoTexto.isEmpty()){
           throw new Exception ("Ano de lançamento não pode ser vazio.");
        }
        
        //Lancamento deve ter exatamento 4 números
        if (!lancamentoTexto.matches("^\\d{4}$")) {
            throw new Exception("Ano de lançamento deve ter exatamente 4 números,EX: 2025");
        }

        // Converte para int
        int lancamentoInt = Integer.parseInt(lancamentoTexto);

        // Verifica se é maior que zero
        if (lancamentoInt <= 0) {
             throw new Exception("Ano de lançamento deve ser maior que zero.");
        }

        
        
        
        //DESENVOLVEDORA
        //Desenvolvedora não pode estar vazio
        if(desenvolvedora.isEmpty()){
           throw new Exception ("Desenvolvedora não pode ser vazio.");
        }
        
        
        //COPIAS
        // Copias não pode estar vazio
        if(copiasTexto.isEmpty()){
           throw new Exception ("Cópias não pode ser vazio.");
        }
        
        //Copias aceita somente  números
        if(!copiasTexto.matches("^[0-9]+$")){
           throw new Exception ("Cópias deve conter somente números.");
        }
        
        // Converte para int
        int copiasInt = Integer.parseInt(copiasTexto);

        // Verifica se é maior que zero
        if (copiasInt <= 0) {
            throw new Exception("Copias deve ser maior que zero.");
}
    }
    
    
    /**
     * Mapeia os atalhos para a tela
     */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblTitulo.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblGenero.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblPlataforma.setDisplayedMnemonic(KeyEvent.VK_3);

        // Alt + 4
        lblLancamento.setDisplayedMnemonic(KeyEvent.VK_4); 
        
        // Alt + 5
        lblDesenvolvedora.setDisplayedMnemonic(KeyEvent.VK_5);   
        
        // Alt + 6
        lblCopias.setDisplayedMnemonic(KeyEvent.VK_6);
        
        // Alt + E
        btnEditar.setMnemonic(KeyEvent.VK_E);
                
        // Alt + C
        btnConfirmar.setMnemonic(KeyEvent.VK_C);
        
        // Alt + X
        btnExcluir.setMnemonic(KeyEvent.VK_X);
        
        // Alt + V
        btnVoltar.setMnemonic(KeyEvent.VK_V);
        
    }
}
