package view;

import dao.UsuarioDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Usuario;
import utilidades.ConectarBD;
import utilidades.GuardarUsuario;

/**
 * Nesta tela se faz o login para entrar no sistema
 * @author guise
 */
public class TelaDeLogin extends javax.swing.JFrame {

   
    
    public TelaDeLogin() {
        initComponents();
        mapearTeclas();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblNomeUsuario = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        cbxTipoUsuario = new javax.swing.JComboBox<>();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(130, 201, 198));

        jLayeredPane1.setBackground(new java.awt.Color(130, 201, 198));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela de login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 51, 153))); // NOI18N
        jLayeredPane1.setForeground(new java.awt.Color(130, 201, 198));
        jLayeredPane1.setToolTipText("Insira os dados do seu login");

        lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNomeUsuario.setLabelFor(txtNomeUsuario);
        lblNomeUsuario.setText("Nome de usuário:");

        txtNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomeUsuario.setToolTipText("Insira nome de usuário (Alt + 1)");
        txtNomeUsuario.setNextFocusableComponent(txtSenha);

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSenha.setToolTipText("Insira a sua senha (Alt + 2)");
        txtSenha.setNextFocusableComponent(cbxTipoUsuario);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSenha.setLabelFor(txtSenha);
        lblSenha.setText("Senha:");

        lblTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTipoUsuario.setLabelFor(cbxTipoUsuario);
        lblTipoUsuario.setText("Tipo de usuário:");

        cbxTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Atendente", "Estoquista", "Gerente", "Supervisor" }));
        cbxTipoUsuario.setToolTipText("Selecione o tipo de usuário(Alt + 3)");
        cbxTipoUsuario.setNextFocusableComponent(btnEntrar);

        btnEntrar.setBackground(new java.awt.Color(9, 132, 127));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setToolTipText("Pressione para entrar com o login (Atalho Alt + E");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblNomeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNomeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEntrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblNomeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEntrar)
                .addGap(25, 25, 25))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeUsuario)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnEntrar)
                .addGap(19, 19, 19))
        );

        txtNomeUsuario.getAccessibleContext().setAccessibleName("Nome de usuário");
        txtSenha.getAccessibleContext().setAccessibleName("Campo senha");
        txtSenha.getAccessibleContext().setAccessibleDescription("Campo para você inserir a sua senha");
        cbxTipoUsuario.getAccessibleContext().setAccessibleName("Tipo de usuário");
        cbxTipoUsuario.getAccessibleContext().setAccessibleDescription("ComboBox para você inserir o tipo de usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        jLayeredPane1.getAccessibleContext().setAccessibleDescription("Insira o seu nome de usuário, senha e tipo de usuário");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        /**
         * Realiza o login e entra no Menu Principal
         */ 
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        try{
            

        
        //Não permite que os campos fiquem vazios
        validarCampos();
        autenticarUsuario();
        verificarUsuario();
        
        MenuPrincipal telaMenuPrincipal = new MenuPrincipal();
        telaMenuPrincipal.setVisible(true);
        dispose();
        
        } catch (Exception e)  {             
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEntrarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeLogin().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JComboBox<String> cbxTipoUsuario;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables

//Métodos usados
    
    
    /**
     * Verifica se os dados do usuário existem na base de dados
     */
    protected void autenticarUsuario (){
        UsuarioDAO dao = new UsuarioDAO();
        
        String usuarioDigitado = txtNomeUsuario.getText();
        String senhaDigitada = txtSenha.getText();
        String tipoUsuario = cbxTipoUsuario.getSelectedItem().toString();
        
        Usuario usuario = dao.autenticar(usuarioDigitado, senhaDigitada, tipoUsuario);
        
        // Se retornar null, o DAO já mostrou a mensagem
        if (usuario == null) {
        return;
        }
        
        else {
        // Guarda o usuário logado em uma variável global
        GuardarUsuario.setUsuario(usuario);
        }
    }
    
    /**
     * Verifica o tipo de usuário que está se conectando no sistema
     * 
     */
    protected void verificarUsuario(){
        Usuario user = GuardarUsuario.getUsuario();
        String usuarioLogado = user.getTipoUsuario();
        String nome = user.getNomeUsuario();
        
        // Determina que tipo usuário está tentando se conectar
        switch (usuarioLogado){
            
            case "Gerente":
            ConectarBD.criarConexao("Gerente", "54321");
            break;
            
            case "Atendente":
            ConectarBD.criarConexao("Atendente", "12345");
            break;
            
            case "Supervisor":
            ConectarBD.criarConexao("Supervisor", "56789");
            break;
            
            case "Estoquista":
            ConectarBD.criarConexao("Estoquista", "98765");
            break;

        default:
            // Conecta como um usuário root por padrão
            ConectarBD.criarConexao("root", "gui2004");
            break;
        }
        
        JOptionPane.showMessageDialog(null, "Olá, " + nome + ", seu tipo de usuário é: " + usuarioLogado +
                                      ". Seja bem-vindo!" );
    }
    
    /**
     * Impede que seja aceito campos vazios
     */ 
    protected void validarCampos() throws Exception {
        
        String nomeUsuario = txtNomeUsuario.getText();
        String senha = txtSenha.getText();
        String tipo = cbxTipoUsuario.getSelectedItem().toString();
        
        
        if (nomeUsuario.isEmpty()){
            throw new Exception ("Campo Nome de usuário não pode ser vazio.");
        }
        
        if (senha.isEmpty()){
            throw new Exception ("Campo Senha não pode ser vazio.");
        }
        
        if (tipo.equals("Selecione")){
            throw new Exception ("Escolha um tipo de usuário.");
        }
    }

    
     /**
      * Mapeia os atalhos para a tela
      */ 
    protected void mapearTeclas(){
        
        
        // Alt + 1
        lblNomeUsuario.setDisplayedMnemonic(KeyEvent.VK_1);
        
        // Alt + 2
        lblSenha.setDisplayedMnemonic(KeyEvent.VK_2);
        
        // Alt + 3
        lblTipoUsuario.setDisplayedMnemonic(KeyEvent.VK_3);        
        
        // Alt + E
        btnEntrar.setMnemonic(KeyEvent.VK_E);
        
    }
}
